// Secrets: an environment variable (upper-cased name) wins; otherwise the project's Vault value, generated by the
// migration and read once per isolate through pos_rpc.secret_value(). Never logged, never returned.
import { asService, rpc } from './db.ts';
import { PosError } from './errors.ts';

export type SecretName = 'pos_session_signing_key' | 'pos_dev_issuer_secret' | 'pos_worker_key';

const cache = new Map<SecretName, string>();

export async function secret(name: SecretName): Promise<string> {
  const cached = cache.get(name);
  if (cached) return cached;
  const fromEnv = Deno.env.get(name.toUpperCase());
  const value = fromEnv && fromEnv.length >= 32
    ? fromEnv
    : await asService({ id: null, role: 'system', requestId: 'secret-load' }, (tx) => rpc<string | null>(tx, 'secret_value', [[name, 'text']]));
  if (!value) throw new PosError('UNAVAILABLE', `secret ${name} is not provisioned`);
  cache.set(name, value);
  return value;
}

export function secretKeyBytes(hexOrText: string): Uint8Array {
  if (/^[0-9a-f]{64,}$/i.test(hexOrText)) {
    const out = new Uint8Array(hexOrText.length / 2);
    for (let i = 0; i < out.length; i++) out[i] = parseInt(hexOrText.slice(i * 2, i * 2 + 2), 16);
    return out;
  }
  return new TextEncoder().encode(hexOrText);
}
