// GENERATED by tool/generate_tokens.dart from schema/design/tokens.json.
// Do not edit by hand: change tokens.json, then run
//   dart run tool/generate_tokens.dart

import 'package:flutter/widgets.dart';

/// The FESS look (docs/14, D-47) as Dart constants.
abstract final class PosTokens {
  /// `color.background.card`
  static const Color colorBackgroundCard = Color(0xFFFFFFFF);

  /// `color.background.home`
  static const Color colorBackgroundHome = Color(0xFFF6F6F7);

  /// `color.background.page`
  static const Color colorBackgroundPage = Color(0xFFFFFFFF);

  /// `color.background.subtle`
  static const Color colorBackgroundSubtle = Color(0xFFF7F7F8);

  /// `color.brand.gold`
  static const Color colorBrandGold = Color(0xFFB79E67);

  /// `color.brand.goldText`
  static const Color colorBrandGoldText = Color(0xFF8A7443);

  /// `color.brand.primary`
  static const Color colorBrandPrimary = Color(0xFF006B55);

  /// `color.brand.primaryDark`
  static const Color colorBrandPrimaryDark = Color(0xFF005747);

  /// `color.brand.primaryLight`
  static const Color colorBrandPrimaryLight = Color(0xFF029073);

  /// `color.line.border`
  static const Color colorLineBorder = Color(0xFFDFDFDF);

  /// `color.line.divider`
  static const Color colorLineDivider = Color(0xFFE0E3E7);

  /// `color.nav.active`
  static const Color colorNavActive = Color(0xFF006B55);

  /// `color.nav.background`
  static const Color colorNavBackground = Color(0xFFFFFFFF);

  /// `color.nav.inactive`
  static const Color colorNavInactive = Color(0xFFD8D8D8);

  /// `color.status.error`
  static const Color colorStatusError = Color(0xFFFF000E);

  /// `color.status.errorText`
  static const Color colorStatusErrorText = Color(0xFFC4000B);

  /// `color.status.info`
  static const Color colorStatusInfo = Color(0xFF2799FF);

  /// `color.status.success`
  static const Color colorStatusSuccess = Color(0xFF249689);

  /// `color.status.successBright`
  static const Color colorStatusSuccessBright = Color(0xFF25BB48);

  /// `color.status.warning`
  static const Color colorStatusWarning = Color(0xFFF9CF58);

  /// `color.text.body`
  static const Color colorTextBody = Color(0xFF4C4C4C);

  /// `color.text.muted`
  static const Color colorTextMuted = Color(0xFFA3A3A3);

  /// `color.text.onPrimary`
  static const Color colorTextOnPrimary = Color(0xFFFFFFFF);

  /// `color.text.primary`
  static const Color colorTextPrimary = Color(0xFF000000);

  /// `component.bottomNav.active`
  static const Color componentBottomNavActive = colorNavActive;

  /// `component.bottomNav.background`
  static const Color componentBottomNavBackground = colorNavBackground;

  /// `component.bottomNav.inactive`
  static const Color componentBottomNavInactive = colorNavInactive;

  /// `component.button.height`
  static const double componentButtonHeight = 45;

  /// `component.button.primary.background`
  static const Color componentButtonPrimaryBackground = colorBrandPrimary;

  /// `component.button.primary.text`
  static const Color componentButtonPrimaryText = Color(0xFFFFFFFF);

  /// `component.button.radius`
  static const double componentButtonRadius = radiusControl;

  /// `component.button.secondary.background`
  static const Color componentButtonSecondaryBackground = colorBrandGold;

  /// `component.button.secondary.text`
  static const Color componentButtonSecondaryText = Color(0xFFFFFFFF);

  /// `component.button.text.size`
  static const double componentButtonTextSize = 14;

  /// `component.button.text.weight`
  static const FontWeight componentButtonTextWeight = FontWeight.w600;

  /// `component.card.background`
  static const Color componentCardBackground = colorBackgroundCard;

  /// `component.card.innerRadius`
  static const double componentCardInnerRadius = 8;

  /// `component.card.radius`
  static const double componentCardRadius = radiusCard;

  /// `component.card.shadow`
  static const BoxShadow componentCardShadow = shadowCard;

  /// `component.header.back.color`
  static const Color componentHeaderBackColor = Color(0xFFFFFFFF);

  /// `component.header.back.iconSize`
  static const double componentHeaderBackIconSize = 12;

  /// `component.header.back.shape`
  static const String componentHeaderBackShape = 'circle';

  /// `component.header.back.size`
  static const double componentHeaderBackSize = 30;

  /// `component.header.background`
  static const Color componentHeaderBackground = colorBrandPrimary;

  /// `component.header.height`
  static const double componentHeaderHeight = 60;

  /// `component.header.paddingX`
  static const double componentHeaderPaddingX = 32;

  /// `component.header.title.color`
  static const Color componentHeaderTitleColor = Color(0xFFFFFFFF);

  /// `component.header.title.size`
  static const double componentHeaderTitleSize = 16;

  /// `component.header.title.weight`
  static const FontWeight componentHeaderTitleWeight = FontWeight.w600;

  /// `component.input.border`
  static const Color componentInputBorder = colorLineDivider;

  /// `component.input.focus`
  static const Color componentInputFocus = colorBrandPrimary;

  /// `component.input.radius`
  static const double componentInputRadius = radiusInput;

  /// `component.input.text`
  static const Color componentInputText = colorTextBody;

  /// `component.listRow.chevron`
  static const Color componentListRowChevron = colorTextMuted;

  /// `component.listRow.description.size`
  static const double componentListRowDescriptionSize = 12;

  /// `component.listRow.description.weight`
  static const FontWeight componentListRowDescriptionWeight = FontWeight.w400;

  /// `component.listRow.divider`
  static const Color componentListRowDivider = colorLineDivider;

  /// `component.listRow.height`
  static const double componentListRowHeight = 80;

  /// `component.listRow.iconColumn`
  static const double componentListRowIconColumn = 70;

  /// `component.listRow.title.size`
  static const double componentListRowTitleSize = 14;

  /// `component.listRow.title.weight`
  static const FontWeight componentListRowTitleWeight = FontWeight.w700;

  /// `component.statusBar.background`
  static const Color componentStatusBarBackground = colorBrandPrimary;

  /// `component.statusBar.foreground`
  static const Color componentStatusBarForeground = Color(0xFFFFFFFF);

  /// `font.fallback`
  static const List<String> fontFallback = <String>[
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'sans-serif',
  ];

  /// `font.family`
  static const String fontFamily = 'Montserrat';

  /// `material.useMaterial3`
  static const bool materialUseMaterial3 = false;

  /// `radius.card`
  static const double radiusCard = 12;

  /// `radius.control`
  static const double radiusControl = 5;

  /// `radius.input`
  static const double radiusInput = 8;

  /// `radius.pill`
  static const double radiusPill = 30;

  /// `shadow.card`
  static const BoxShadow shadowCard = BoxShadow(
    color: Color(0x1A000000),
    offset: Offset(0, 2),
    blurRadius: 4,
  );

  /// `type.phone.body.size`
  static const double typePhoneBodySize = 14;

  /// `type.phone.body.weight`
  static const FontWeight typePhoneBodyWeight = FontWeight.w600;

  /// `type.phone.bodyRegular.size`
  static const double typePhoneBodyRegularSize = 14;

  /// `type.phone.bodyRegular.weight`
  static const FontWeight typePhoneBodyRegularWeight = FontWeight.w400;

  /// `type.phone.button.size`
  static const double typePhoneButtonSize = 14;

  /// `type.phone.button.weight`
  static const FontWeight typePhoneButtonWeight = FontWeight.w600;

  /// `type.phone.caption.size`
  static const double typePhoneCaptionSize = 12;

  /// `type.phone.caption.weight`
  static const FontWeight typePhoneCaptionWeight = FontWeight.w400;

  /// `type.phone.headline.size`
  static const double typePhoneHeadlineSize = 24;

  /// `type.phone.headline.weight`
  static const FontWeight typePhoneHeadlineWeight = FontWeight.w500;

  /// `type.phone.title.size`
  static const double typePhoneTitleSize = 16;

  /// `type.phone.title.weight`
  static const FontWeight typePhoneTitleWeight = FontWeight.w600;

  /// `type.phone.titleLarge.size`
  static const double typePhoneTitleLargeSize = 22;

  /// `type.phone.titleLarge.weight`
  static const FontWeight typePhoneTitleLargeWeight = FontWeight.w600;

  /// `version`
  static const String version = '1.0.0';
}
