// Generates lib/src/core/theme/tokens.g.dart from schema/design/tokens.json,
// the single source of the FESS look (docs/14, D-47). Run from
// packages/fess_pos:
//
//   dart run tool/generate_tokens.dart
//
// test/core/theme/tokens_test.dart fails when the output is stale.

import 'dart:convert';
import 'dart:io';

const String tokensPath = '../../schema/design/tokens.json';
const String outputPath = 'lib/src/core/theme/tokens.g.dart';

void main() {
  final json =
      jsonDecode(File(tokensPath).readAsStringSync()) as Map<String, Object?>;
  File(outputPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(generateTokensDart(json));
  // The output is formatted like any other source; the staleness test
  // compares it with the generator modulo whitespace.
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    outputPath,
  ]);
  if (format.exitCode != 0) {
    stderr.write(format.stderr);
    exitCode = format.exitCode;
    return;
  }
  stdout.writeln('wrote $outputPath');
}

/// Top-level metadata that isn't a design value.
const Set<String> _skipTopLevel = {'name', 'description', 'source', 'assets'};

/// Keys that annotate a token rather than being one.
const Set<String> _skipKeys = {'note', 'derived', 'source'};

final RegExp _hexColor = RegExp(r'^#[0-9A-Fa-f]{6}$');
final RegExp _shadow = RegExp(
  r'^(-?\d+(?:\.\d+)?)(?:px)?\s+(-?\d+(?:\.\d+)?)(?:px)?\s+'
  r'(\d+(?:\.\d+)?)(?:px)?\s+rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$',
);

/// The Dart source for [tokens].
String generateTokensDart(Map<String, Object?> tokens) {
  final flat = <String, Object?>{};

  void walk(List<String> path, Object? node) {
    if (node is Map<String, Object?>) {
      if (node.containsKey('value')) {
        flat[path.join('.')] = node['value'];
        return;
      }
      for (final e in node.entries) {
        if (_skipKeys.contains(e.key)) continue;
        walk([...path, e.key], e.value);
      }
    } else {
      flat[path.join('.')] = node;
    }
  }

  for (final e in tokens.entries) {
    if (_skipTopLevel.contains(e.key)) continue;
    walk([e.key], e.value);
  }

  String typeOf(String path, Object? v) {
    if (v is bool) return 'bool';
    if (v is num) return path.endsWith('.weight') ? 'FontWeight' : 'double';
    if (v is List) return 'List<String>';
    if (v is String) {
      if (_hexColor.hasMatch(v)) return 'Color';
      if (_shadow.hasMatch(v)) return 'BoxShadow';
      if (flat.containsKey(v)) return typeOf(v, flat[v]);
      return 'String';
    }
    throw FormatException('unsupported token value at $path', '$v');
  }

  String literal(String path, Object? v) {
    if (v is bool) return '$v';
    if (v is num) {
      if (path.endsWith('.weight')) return 'FontWeight.w$v';
      return '$v';
    }
    if (v is List) {
      return '<String>[${v.map((s) => _str('$s')).join(', ')}]';
    }
    if (v is String) {
      if (_hexColor.hasMatch(v)) {
        return 'Color(0xFF${v.substring(1).toUpperCase()})';
      }
      final m = _shadow.firstMatch(v);
      if (m != null) {
        final alpha = (double.parse(m.group(7)!) * 255).round();
        final argb = [
          alpha,
          int.parse(m.group(4)!),
          int.parse(m.group(5)!),
          int.parse(m.group(6)!),
        ].map((c) => c.toRadixString(16).padLeft(2, '0')).join();
        return 'BoxShadow(color: Color(0x${argb.toUpperCase()}), '
            'offset: Offset(${m.group(1)}, ${m.group(2)}), '
            'blurRadius: ${m.group(3)})';
      }
      if (flat.containsKey(v)) return _name(v);
      return _str(v);
    }
    throw FormatException('unsupported token value at $path', '$v');
  }

  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/generate_tokens.dart from '
      'schema/design/tokens.json.',
    )
    ..writeln('// Do not edit by hand: change tokens.json, then run')
    ..writeln('//   dart run tool/generate_tokens.dart')
    ..writeln()
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln('/// The FESS look (docs/14, D-47) as Dart constants.')
    ..writeln('abstract final class PosTokens {');
  final paths = flat.keys.toList()..sort();
  for (var i = 0; i < paths.length; i++) {
    final path = paths[i];
    final v = flat[path];
    final type = typeOf(path, v);
    final line = '  static const $type ${_name(path)} = ${literal(path, v)};';
    if (i > 0) out.writeln();
    out.writeln('  /// `$path`');
    if (line.length <= 80) {
      out.writeln(line);
    } else {
      out
        ..writeln('  static const $type ${_name(path)} =')
        ..writeln('      ${literal(path, v)};');
    }
  }
  out.writeln('}');
  return out.toString();
}

/// `component.header.back.iconSize` → `componentHeaderBackIconSize`.
String _name(String path) {
  final parts = path.split('.');
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String _str(String s) {
  final escaped = s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}
