// Generates lib/src/core/config/config_defaults.g.dart from
// schema/config/defaults.json and remote-config.schema.json: the bundled
// safe defaults (docs/13 §5) and every key's type and bounds. Run from
// packages/fess_pos:
//
//   dart run tool/generate_config_defaults.dart
//
// test/core/remote_config_test.dart fails when the output is stale.

import 'dart:convert';
import 'dart:io';

const String defaultsPath = '../../schema/config/defaults.json';
const String schemaPath = '../../schema/config/remote-config.schema.json';
const String outputPath = 'lib/src/core/config/config_defaults.g.dart';

void main() {
  final defaults =
      jsonDecode(File(defaultsPath).readAsStringSync()) as Map<String, Object?>;
  final schema =
      jsonDecode(File(schemaPath).readAsStringSync()) as Map<String, Object?>;
  File(outputPath)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(generateConfigDefaultsDart(defaults, schema));
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    outputPath,
  ]);
  if (format.exitCode != 0) {
    stderr.write(format.stderr);
    exitCode = format.exitCode;
    return;
  }
  stdout.writeln('wrote $outputPath');
}

/// The Dart source for [defaults] and the leaves of [schema].
String generateConfigDefaultsDart(
  Map<String, Object?> defaults,
  Map<String, Object?> schema,
) {
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_config_defaults.dart from')
    ..writeln('// schema/config/. Do not edit by hand.')
    ..writeln()
    ..writeln("import 'package:fess_pos/src/core/config/config_leaf.dart';")
    ..writeln()
    ..writeln('/// The bundled safe defaults (schema/config/defaults.json,')
    ..writeln('/// docs/13 §5): behaviour only, never endpoints or secrets.')
    ..writeln(
      'const Map<String, Object?> bundledConfigDefaults = '
      '${_literal(defaults)};',
    )
    ..writeln()
    ..writeln('/// Every key: its type and bounds')
    ..writeln('/// (schema/config/remote-config.schema.json).')
    ..writeln('const Map<String, ConfigLeaf> configLeaves = {');
  void walk(String prefix, Map<String, Object?> node) {
    final properties = node['properties'];
    if (properties is! Map<String, Object?>) return;
    for (final e in properties.entries) {
      final path = prefix.isEmpty ? e.key : '$prefix.${e.key}';
      final child = e.value! as Map<String, Object?>;
      if (child['type'] == 'object' && child['properties'] is Map) {
        walk(path, child);
      } else {
        out.writeln("  '$path': ${_leaf(path, child)},");
      }
    }
  }

  walk('', schema);
  out.writeln('};');
  return out.toString();
}

String _leaf(String path, Map<String, Object?> node) {
  var nullable = false;
  var typed = node;
  String? type;
  final declared = node['type'];
  if (declared is String) {
    type = declared;
  } else if (declared is List) {
    nullable = declared.contains('null');
    type = declared.whereType<String>().firstWhere((t) => t != 'null');
  } else if (node['anyOf'] is List || node['oneOf'] is List) {
    final options = ((node['anyOf'] ?? node['oneOf'])! as List)
        .cast<Map<String, Object?>>();
    nullable = options.any((o) => o['type'] == 'null');
    final base = options.where((o) => o['type'] != 'null').toList();
    if (base.length != 1 || base.single['type'] is! String) {
      throw FormatException('$path: unsupported anyOf in the config schema');
    }
    typed = base.single;
    type = typed['type']! as String;
  } else if (node['enum'] is List) {
    type = 'string';
  } else {
    throw FormatException('$path: no type in the config schema');
  }
  final values = (typed['enum'] ?? node['enum']) as List?;
  nullable = nullable || (values?.contains(null) ?? false);
  final kind = switch (type) {
    'integer' => 'integer',
    'number' => 'number',
    'boolean' => 'boolean',
    'string' => 'string',
    'array' => 'array',
    'object' => 'object',
    _ => throw FormatException('$path: type $type is not supported'),
  };
  final args = [
    'ConfigType.$kind',
    if (nullable) 'nullable: true',
    if (typed['minimum'] != null) 'min: ${typed['minimum']}',
    if (typed['maximum'] != null) 'max: ${typed['maximum']}',
    if (values != null)
      'values: [${values.whereType<String>().map(_string).join(', ')}]',
  ];
  return 'ConfigLeaf(${args.join(', ')})';
}

String _literal(Object? value) => switch (value) {
  null => 'null',
  final bool b => '$b',
  final num n => '$n',
  final String s => _string(s),
  final List<Object?> l => '<Object?>[${l.map(_literal).join(', ')}]',
  final Map<String, Object?> m =>
    '<String, Object?>{${m.entries.map(_entry).join(', ')}}',
  _ => throw FormatException('unsupported JSON value ${value.runtimeType}'),
};

String _entry(MapEntry<String, Object?> e) =>
    '${_string(e.key)}: ${_literal(e.value)}';

/// A single-quoted Dart string literal.
String _string(String s) {
  final escaped = s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}
