// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    moduleMeta,
    syncState,
    outbox,
    cachedDocuments,
  ];
  late final Shape0 moduleMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'module_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 syncState = Shape0(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 outbox = Shape1(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_2,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cachedDocuments = Shape2(
    source: i0.VersionedTable(
      entityName: 'cached_documents',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_22, _column_23, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deviceSeq =>
      columnsByName['device_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get typeVersion =>
      columnsByName['type_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lane =>
      columnsByName['lane']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get envelope =>
      columnsByName['envelope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payloadHash =>
      columnsByName['payload_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get bytes =>
      columnsByName['bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get receiptState =>
      columnsByName['receipt_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get receipt =>
      columnsByName['receipt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextAttemptMs =>
      columnsByName['next_attempt_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get entityRef =>
      columnsByName['entity_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMs =>
      columnsByName['created_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get committedAtMs =>
      columnsByName['committed_at_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'device_seq',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'type_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'lane',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'envelope',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bytes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'receipt_state',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'receipt',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_attempt_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'committed_at_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hash =>
      columnsByName['hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    moduleMeta,
    syncState,
    outbox,
    cachedDocuments,
    jobs,
    reviews,
    definitionVersions,
    activeDefinitions,
  ];
  late final Shape0 moduleMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'module_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 syncState = Shape0(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 outbox = Shape1(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_2,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cachedDocuments = Shape2(
    source: i0.VersionedTable(
      entityName: 'cached_documents',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_22, _column_23, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 jobs = Shape3(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_24,
        _column_25,
        _column_2,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 reviews = Shape4(
    source: i0.VersionedTable(
      entityName: 'reviews',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 definitionVersions = Shape5(
    source: i0.VersionedTable(
      entityName: 'definition_versions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(version_id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_0,
        _column_27,
        _column_37,
        _column_38,
        _column_39,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 activeDefinitions = Shape6(
    source: i0.VersionedTable(
      entityName: 'active_definitions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(context, kind, "key")'],
      columns: [_column_40, _column_36, _column_0, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reference =>
      columnsByName['reference']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get assignedToMe =>
      columnsByName['assigned_to_me']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get bankId =>
      columnsByName['bank_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get scheduledStartMs =>
      columnsByName['scheduled_start_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reference',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'assigned_to_me',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (assigned_to_me IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bank_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'scheduled_start_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jobId =>
      columnsByName['job_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get inspectionId =>
      columnsByName['inspection_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempt =>
      columnsByName['attempt']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get decision =>
      columnsByName['decision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get decidedAt =>
      columnsByName['decided_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'job_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'inspection_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempt',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'decision',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'decided_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get versionId =>
      columnsByName['version_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get familyId =>
      columnsByName['family_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bankId =>
      columnsByName['bank_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get specVersion =>
      columnsByName['spec_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hash =>
      columnsByName['hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get body =>
      columnsByName['body']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'family_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'spec_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get context =>
      columnsByName['context']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get versionId =>
      columnsByName['version_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'context',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    moduleMeta,
    syncState,
    outbox,
    cachedDocuments,
    jobs,
    reviews,
    definitionVersions,
    activeDefinitions,
    tileCacheIndex,
  ];
  late final Shape0 moduleMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'module_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 syncState = Shape0(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 outbox = Shape1(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_2,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cachedDocuments = Shape2(
    source: i0.VersionedTable(
      entityName: 'cached_documents',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_22, _column_23, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 jobs = Shape3(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_24,
        _column_25,
        _column_2,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 reviews = Shape4(
    source: i0.VersionedTable(
      entityName: 'reviews',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 definitionVersions = Shape5(
    source: i0.VersionedTable(
      entityName: 'definition_versions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(version_id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_0,
        _column_27,
        _column_37,
        _column_38,
        _column_39,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 activeDefinitions = Shape6(
    source: i0.VersionedTable(
      entityName: 'active_definitions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(context, kind, "key")'],
      columns: [_column_40, _column_36, _column_0, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 tileCacheIndex = Shape7(
    source: i0.VersionedTable(
      entityName: 'tile_cache_index',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_41, _column_11, _column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get bytes =>
      columnsByName['bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAtMs =>
      columnsByName['fetched_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUsedMs =>
      columnsByName['last_used_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched_at_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_used_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    moduleMeta,
    syncState,
    outbox,
    cachedDocuments,
    jobs,
    reviews,
    definitionVersions,
    activeDefinitions,
    tileCacheIndex,
    inspections,
    evidence,
  ];
  late final Shape0 moduleMeta = Shape0(
    source: i0.VersionedTable(
      entityName: 'module_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape0 syncState = Shape0(
    source: i0.VersionedTable(
      entityName: 'sync_state',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 outbox = Shape1(
    source: i0.VersionedTable(
      entityName: 'outbox',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_2,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cachedDocuments = Shape2(
    source: i0.VersionedTable(
      entityName: 'cached_documents',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_22, _column_23, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 jobs = Shape3(
    source: i0.VersionedTable(
      entityName: 'jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_24,
        _column_25,
        _column_2,
        _column_26,
        _column_27,
        _column_28,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 reviews = Shape4(
    source: i0.VersionedTable(
      entityName: 'reviews',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 definitionVersions = Shape5(
    source: i0.VersionedTable(
      entityName: 'definition_versions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(version_id)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_0,
        _column_27,
        _column_37,
        _column_38,
        _column_39,
        _column_22,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 activeDefinitions = Shape6(
    source: i0.VersionedTable(
      entityName: 'active_definitions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(context, kind, "key")'],
      columns: [_column_40, _column_36, _column_0, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 tileCacheIndex = Shape7(
    source: i0.VersionedTable(
      entityName: 'tile_cache_index',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_41, _column_11, _column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 inspections = Shape8(
    source: i0.VersionedTable(
      entityName: 'inspections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_29,
        _column_44,
        _column_31,
        _column_25,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 evidence = Shape9(
    source: i0.VersionedTable(
      entityName: 'evidence',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_3,
        _column_30,
        _column_29,
        _column_44,
        _column_62,
        _column_63,
        _column_5,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_12,
        _column_20,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jobId =>
      columnsByName['job_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attempt =>
      columnsByName['attempt']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get formVersionId =>
      columnsByName['form_version_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get formHash =>
      columnsByName['form_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get flowVersionId =>
      columnsByName['flow_version_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get flowHash =>
      columnsByName['flow_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jobSchemaVersionId =>
      columnsByName['job_schema_version_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get configVersionId =>
      columnsByName['config_version_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contextSnapshot =>
      columnsByName['context_snapshot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get geofence =>
      columnsByName['geofence']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get integrity =>
      columnsByName['integrity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionTokenId =>
      columnsByName['session_token_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionToken =>
      columnsByName['session_token']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startedAtDevice =>
      columnsByName['started_at_device']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get draft =>
      columnsByName['draft']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get currentStep =>
      columnsByName['current_step']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get submittedAtDevice =>
      columnsByName['submitted_at_device']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startedEnvelopeId =>
      columnsByName['started_envelope_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get submissionEnvelopeId =>
      columnsByName['submission_envelope_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'form_version_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'form_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'flow_version_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'flow_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'job_schema_version_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'config_version_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'context_snapshot',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'geofence',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'integrity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_token_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_token',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'started_at_device',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'draft',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'current_step',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'submitted_at_device',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'started_envelope_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'submission_envelope_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get inspectionId =>
      columnsByName['inspection_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jobId =>
      columnsByName['job_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fieldKey =>
      columnsByName['field_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mime =>
      columnsByName['mime']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get size =>
      columnsByName['size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get width =>
      columnsByName['width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get height =>
      columnsByName['height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get capturedAtDevice =>
      columnsByName['captured_at_device']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get capturedMonotonicMs =>
      columnsByName['captured_monotonic_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isMocked =>
      columnsByName['is_mocked']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get meta =>
      columnsByName['meta']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get bytes =>
      columnsByName['bytes']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAtMs =>
      columnsByName['created_at_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'field_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mime',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sha256',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_66(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'width',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'height',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'captured_at_device',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'captured_monotonic_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_mocked',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_mocked IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meta',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<i2.Uint8List> _column_74(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'bytes',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
