#!/usr/bin/env node
// Generates the Postman collection and environment templates for the module-facing POS API v1 (T2-31, D-50).
//   node tools/postman/build.mjs
// Scripts are written below as real functions, so they parse, and are emitted as Postman script lines. Outputs, next to
// this file: the collection, a QA environment template and a production environment template (blank keys; fill them in,
// or run provision-qa.ts for a ready QA file). Production is read-only in the collection: non-GET requests are skipped.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const REFS = { qa: 'ysbgdxhdexpjvmlnjofc', production: 'zqunqunjdjhyriqsvzfr' };

/** A function's body as Postman script lines. */
function lines(fn) {
  const src = fn.toString();
  const rows = src.slice(src.indexOf('{') + 1, src.lastIndexOf('}')).split('\n');
  while (rows.length && !rows[0].trim()) rows.shift();
  while (rows.length && !rows[rows.length - 1].trim()) rows.pop();
  const indent = Math.min(...rows.filter((r) => r.trim()).map((r) => r.match(/^ */)[0].length));
  return rows.map((r) => r.slice(indent));
}

const APIKEY = { key: 'apikey', value: '{{publishableKey}}', type: 'text' };
const JSON_CT = { key: 'content-type', value: 'application/json', type: 'text' };
const bearer = (value) => ({ type: 'bearer', bearer: [{ key: 'token', value, type: 'string' }] });
const NOAUTH = { type: 'noauth' };

function request(name, o) {
  const item = {
    name,
    request: { method: o.method ?? 'POST', header: o.headers ?? [], url: o.url, auth: o.auth ?? NOAUTH, description: o.description ?? '' },
    event: [],
  };
  if (o.body !== undefined) {
    item.request.body = {
      mode: 'raw',
      raw: typeof o.body === 'string' ? o.body : JSON.stringify(o.body, null, 2),
      options: { raw: { language: o.language ?? 'json' } },
    };
  }
  if (o.pre) item.event.push({ listen: 'prerequest', script: { type: 'text/javascript', exec: lines(o.pre) } });
  if (o.test) {
    // testVars become constants at the top of the emitted script (a closure variable would not survive fn.toString()).
    const consts = Object.entries(o.testVars ?? {}).map(([k, v]) => `const ${k} = ${JSON.stringify(v)};`);
    item.event.push({ listen: 'test', script: { type: 'text/javascript', exec: [...consts, ...lines(o.test)] } });
  }
  return item;
}
const folder = (name, description, item) => ({ name, description, item });
const api = (path) => `{{apiBaseUrl}}${path}`;
const agentPost = (name, path, o) =>
  request(name, { url: api(path), headers: [APIKEY, JSON_CT], auth: bearer('{{accessToken}}'), ...o });
const ingest = (name, description, pre, test) => agentPost(name, '/v1/ingest', { body: '{{ingestBody}}', description, pre, test });
const adminPost = (name, path, o) =>
  request(name, { url: api(`/v1/admin${path}`), headers: [APIKEY, JSON_CT], auth: bearer('{{adminToken}}'), ...o });

// ── collection-level pre-request: shared helpers, environment guard, request id ───────────────────
function collectionPre() {
  // Shared helpers for every script in this collection:  const pos = eval(pm.variables.get('posLib'));
  // Generated by fess-pos/tools/postman/build.mjs — edit it there, not in Postman.
  function posLib() {
    const C = require('crypto-js');
    const hex = (n, width) => n.toString(16).padStart(width, '0');
    const iso = (d) => (d || new Date()).toISOString();

    // RFC 9562 UUIDv7: time-ordered, as the module generates ids (docs/03 §7). Test ids only, so Math.random is fine.
    function uuidv7() {
      let r = '';
      for (let i = 0; i < 20; i++) r += hex(Math.floor(Math.random() * 16), 1);
      const h = hex(Date.now(), 12) + '7' + r.slice(1, 4) + hex((parseInt(r.slice(4, 6), 16) & 0x3f) | 0x80, 2) + r.slice(6);
      return h.slice(0, 8) + '-' + h.slice(8, 12) + '-' + h.slice(12, 16) + '-' + h.slice(16, 20) + '-' + h.slice(20);
    }

    // RFC 8785 (JCS) for the values an envelope carries: keys sorted by UTF-16 code unit, ECMAScript number and string
    // serialisation (which JSON.stringify already follows). payload_hash = sha256(JCS(payload)) (docs/12 §11).
    function canonical(v) {
      if (v === null || typeof v !== 'object') return JSON.stringify(v);
      if (Array.isArray(v)) return '[' + v.map((x) => (x === undefined ? 'null' : canonical(x))).join(',') + ']';
      return '{' + Object.keys(v).filter((k) => v[k] !== undefined).sort().map((k) => JSON.stringify(k) + ':' + canonical(v[k])).join(',') + '}';
    }
    const sha256 = (s) => C.SHA256(C.enc.Utf8.parse(s)).toString(C.enc.Hex);
    const hash = (v) => sha256(canonical(v));

    const getJson = (name, fallback) => {
      const v = pm.collectionVariables.get(name);
      try {
        return v ? JSON.parse(v) : fallback;
      } catch (e) {
        return fallback;
      }
    };
    const setJson = (name, v) => pm.collectionVariables.set(name, JSON.stringify(v));
    function need(name, hint) {
      const v = pm.collectionVariables.get(name) || pm.environment.get(name);
      if (!v) throw new Error('Missing ' + name + ': ' + hint);
      return v;
    }
    function counter(name, start, step) {
      const n = Number(pm.collectionVariables.get(name) || start) + step;
      pm.collectionVariables.set(name, String(n));
      return n;
    }

    // Every device write is an envelope (docs/12 §4): UUIDv7 id, JCS payload hash, per-device sequence number.
    function envelope(type, payload, id) {
      return {
        api_version: '1', id: id || uuidv7(), type, type_version: 1, payload_hash: hash(payload),
        device_id: need('deviceId', 'run "Exchange host token" first'), session_id: pm.collectionVariables.get('sessionId') || null,
        device_seq: counter('deviceSeq', 0, 1), module_version: pm.environment.get('moduleVersion') || '0.1.0', client_type: 'native',
        created_at_device: iso(), monotonic_ms: counter('monotonicMs', 1000, 1500), payload,
      };
    }
    function setIngestBody(envelopes) {
      pm.variables.set('ingestBody', JSON.stringify({ envelopes }));
      setJson('lastEnvelopes', envelopes);
    }
    function checkReceipts(expected) {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const body = pm.response.json();
      const sent = getJson('lastEnvelopes', []);
      (body.receipts || []).forEach((r, i) => {
        const type = (sent[i] && sent[i].type) || '?';
        pm.test('receipt ' + (i + 1) + ' · ' + type + ' → ' + r.state + (r.error ? ' (' + r.error.code + ')' : ''), () => {
          pm.expect(r.durable, 'landed on the server').to.eql(true);
          if (expected) pm.expect(expected, 'expected receipt state').to.include(r.state);
          if (r.stored_hash && sent[i] && r.state !== 'conflict') pm.expect(r.stored_hash, 'server stored exactly what was sent').to.eql(sent[i].payload_hash);
        });
        if (r.error) console.log(type + ' ' + r.state + ': ' + JSON.stringify(r.error));
      });
      return body.receipts || [];
    }
    function checkError(status, code) {
      pm.test('HTTP ' + status, () => pm.response.to.have.status(status));
      const b = pm.response.json();
      pm.test('error ' + code + ' with an explicit retryable flag', () => {
        pm.expect(b.error.code).to.eql(code);
        pm.expect(b.error.retryable).to.be.a('boolean');
        pm.expect(b.request_id).to.be.a('string');
      });
    }

    // RFC 6238 TOTP (SHA-1, 6 digits, 30 s) for the QA test admin's MFA step.
    function totp(secret) {
      const A = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
      let bits = '';
      for (const ch of String(secret).replace(/=+$/, '').replace(/\s+/g, '').toUpperCase()) {
        const i = A.indexOf(ch);
        if (i < 0) throw new Error('adminTotpSecret is not base32');
        bits += i.toString(2).padStart(5, '0');
      }
      let key = '';
      for (let i = 0; i + 8 <= bits.length; i += 8) key += hex(parseInt(bits.slice(i, i + 8), 2), 2);
      const mac = C.HmacSHA1(C.enc.Hex.parse(hex(Math.floor(Date.now() / 30000), 16)), C.enc.Hex.parse(key)).toString(C.enc.Hex);
      const off = parseInt(mac.slice(-1), 16);
      return String((parseInt(mac.slice(off * 2, off * 2 + 8), 16) & 0x7fffffff) % 1000000).padStart(6, '0');
    }

    // Answers for the seeded global site_inspection v1 form: a standard-risk job at a standalone site, premises
    // "complex" (2 external + 2 internal photos, no shopfront). The same set as tools/scenarios/lib/inspection.ts.
    function answersFor(ctx, insp) {
      const ids = (field) => insp.evidence.filter((c) => c.field_key === field).map((c) => c.id);
      const end = new Date(Date.parse(insp.started) + 35 * 60000);
      const a = {
        inspection_date: { v: insp.context.today, computed: true },
        merchant_name: { v: ctx.job.merchant_name, prefilled: true },
        address: { v: ctx.job.address, prefilled: true },
        registration_date: { v: '2019-03-01' },
        time_in_business: { v: { value: 6, unit: 'years' } },
        nature_of_business: { v: 'General dealer: groceries, airtime and household goods' },
        contact_person: { v: 'Thandi Mokoena' },
        contact_number: { v: '+27821234567' },
        business_hours: { v: { weekdays: { open: '08:00', close: '18:00' }, saturday: { open: '08:00', close: '14:00' }, sunday: 'closed', public_holidays: 'closed' } },
        payment_methods: { v: ['pos', 'cash', 'qr'] },
        premises_type: { v: 'complex' },
        property_tenure: { v: 'leased' },
        floor_area_m2: { v: 45 },
        other_businesses: { v: 'None observed' },
        office_equipment: { v: 'Card terminal, till, laptop' },
        equipment_compatible: { v: true },
        external_photos: { v: ids('external_photos') },
        internal_photos: { v: ids('internal_photos') },
        inventory_sufficient: { v: true },
        appears_legitimate: { v: true },
        customers_present: { v: true },
        other_bank_evidence: { v: false },
        goods_delivered_at_pos: { v: true },
        delivered_at_pos_pct: { v: 80 },
        ecommerce_sales: { v: true },
        ecommerce_pct: { v: 15 },
        refund_policy: { v: 'Exchange within 7 days with a slip' },
        delivery_policy: { v: 'no' },
        data_security: { v: 'Terminal kept behind the counter; slips filed in a locked drawer; cards never leave the customer.' },
        interviewee_name: { v: 'Thandi Mokoena' },
        interviewee_designation: { v: 'Owner' },
        merchant_certification: { v: { given: true, text_version_id: ctx.declarations.merchant, at: iso(new Date(end.getTime() - 5 * 60000)), by_name: 'Thandi Mokoena' } },
        interviewee_signature: { v: ids('interviewee_signature')[0] },
        agent_declaration: { v: { accepted: true, declaration_version_id: ctx.declarations.agent, accepted_at: iso(end) } },
      };
      if (ctx.job.mcc) {
        a.mcc_code = { v: ctx.job.mcc.code, prefilled: true };
        a.mcc_description = { v: ctx.job.mcc.description, prefilled: true };
      }
      return { answers: a, end };
    }

    return { uuidv7, canonical, sha256, hash, iso, getJson, setJson, need, envelope, setIngestBody, checkReceipts, checkError, totp, answersFor };
  }
  pm.variables.set('posLib', '(' + posLib.toString() + ')()');
  const pos = eval(pm.variables.get('posLib'));

  // Which environment? Production is read-only in this collection (instructions §10–11): no test data, no writes.
  const env = pm.environment.get('env');
  if (env !== 'qa' && env !== 'production') throw new Error('Choose the "FESS POS — QA" or "FESS POS — production" environment first.');
  if (env === 'production' && pm.request.method !== 'GET') {
    console.warn('Skipped on production (read-only in this collection): ' + pm.info.requestName);
    if (pm.execution && pm.execution.skipRequest) pm.execution.skipRequest();
    else throw new Error('Production is read-only in this collection; only GET requests run there.');
  }
  pm.request.headers.upsert({ key: 'x-pos-request-id', value: 'pm-' + pos.uuidv7() });
}

// ── requests ────────────────────────────────────────────────────────────────────────────────────
const health = folder('00 Health', 'Public, no key needed. `?deep=1` also checks the database.', [
  request('Health', {
    method: 'GET',
    url: api('/v1/health?deep=1'),
    test: function () {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const b = pm.response.json();
      pm.test('talking to the ' + pm.environment.get('env') + ' backend', () => pm.expect(b.env).to.eql(pm.environment.get('env')));
      pm.test('database reachable', () => pm.expect(b.db).to.eql('ok'));
    },
  }),
]);

const adminOk = function () {
  pm.test('HTTP 2xx', () => pm.expect(pm.response.code).to.be.oneOf([200, 201]));
};

const setup = folder('01 QA setup (test admin)', [
  'QA only. Signs in as the QA test admin (password; the TOTP step runs only if the admin has one set up, D-96), makes a fresh job for the test',
  'agent (create, log a contact attempt, confirm the appointment, allocate) and mints the host token a host app would hold',
  'for that agent, using the stand-in issuer `pos_dev`. Production refuses the stand-in issuer, and this collection skips',
  'every non-GET request there. Run it again whenever you want a fresh job.',
].join(' '), [
  request('Admin sign-in (password)', {
    url: '{{supabaseUrl}}/auth/v1/token?grant_type=password',
    headers: [APIKEY, JSON_CT],
    body: { email: '{{adminEmail}}', password: '{{adminPassword}}' },
    test: function () {
      pm.test('signed in', () => pm.response.to.have.status(200));
      const s = pm.response.json();
      pm.collectionVariables.set('adminAal1Token', s.access_token);
      // A password session is enough while admin.require_mfa is off (D-96); the next request upgrades it when a TOTP
      // factor is set up, so the collection works whichever way the setting is.
      pm.collectionVariables.set('adminToken', s.access_token);
      const f = ((s.user && s.user.factors) || []).find((x) => x.factor_type === 'totp' && x.status === 'verified');
      if (f) pm.collectionVariables.set('adminFactorId', f.id);
      else pm.collectionVariables.unset('adminFactorId');
    },
  }),
  request('Admin second step (TOTP → aal2, only if set up)', {
    url: '{{supabaseUrl}}/auth/v1/factors/{{adminFactorId}}/verify',
    headers: [APIKEY, JSON_CT],
    auth: bearer('{{adminAal1Token}}'),
    body: { challenge_id: '{{challengeId}}', code: '{{totpCode}}' },
    pre: function () {
      if (!pm.collectionVariables.get('adminFactorId') || !pm.environment.get('adminTotpSecret')) {
        pm.execution.skipRequest();
        return;
      }
      const pos = eval(pm.variables.get('posLib'));
      const secret = pos.need('adminTotpSecret', "the QA test admin's TOTP secret (provision-qa.ts writes it into your environment)");
      pm.sendRequest({
        url: pm.environment.get('supabaseUrl') + '/auth/v1/factors/' + pos.need('adminFactorId', 'run "Admin sign-in" first') + '/challenge',
        method: 'POST',
        header: [
          { key: 'apikey', value: pm.environment.get('publishableKey') },
          { key: 'authorization', value: 'Bearer ' + pos.need('adminAal1Token', 'run "Admin sign-in" first') },
          { key: 'content-type', value: 'application/json' },
        ],
        body: { mode: 'raw', raw: '{}' },
      }, (err, res) => {
        if (err) throw err;
        pm.variables.set('challengeId', res.json().id);
        pm.variables.set('totpCode', pos.totp(secret));
      });
    },
    test: function () {
      pm.test('MFA verified', () => pm.response.to.have.status(200));
      pm.collectionVariables.set('adminToken', pm.response.json().access_token);
    },
  }),
  adminPost('Create a job for the test agent', '/jobs', {
    body: {
      bank_id: '{{testBankId}}', merchant_name: 'Postman Spaza {{$timestamp}}', trading_name: null, external_ref: 'PM-{{$timestamp}}',
      address: { line1: '12 Vilakazi St', suburb: 'Orlando West', city: 'Soweto', province: 'Gauteng', postal_code: '1804', country: 'ZA' },
      location: { lat: -26.2385, lng: 27.9087 }, location_source: 'pinned', location_type: 'standalone', mcc_code: '5411',
      contact: { name: 'Sipho Postman', phone: '+27823450098' }, notes: 'Postman test job (QA dummy data)',
      attributes: { branch_code: '632005', account_manager: 'Postman', risk_tier: 'standard' },
    },
    test: function () {
      pm.test('job created', () => pm.expect(pm.response.code).to.be.oneOf([200, 201]));
      const j = pm.response.json();
      pm.collectionVariables.set('jobId', j.id);
      pm.collectionVariables.set('jobReference', j.reference);
      console.log('job ' + j.reference);
    },
  }),
  adminPost('Log a contact attempt', '/jobs/{{jobId}}/contact-attempts', {
    body: { channel: 'phone', outcome: 'confirmed', contact_name: 'Sipho Postman' },
    test: adminOk,
  }),
  adminPost('Confirm the appointment', '/jobs/{{jobId}}/schedule', {
    body: {
      scheduled_start: '{{scheduleStart}}', scheduled_end: '{{scheduleEnd}}',
      onsite_contact: { name: 'Sipho Postman', phone: '+27823450098', role: 'Owner' }, note: 'Confirmed by phone (Postman)',
    },
    pre: function () {
      const start = new Date(Date.now() - 30 * 60000);
      pm.variables.set('scheduleStart', start.toISOString());
      pm.variables.set('scheduleEnd', new Date(start.getTime() + 4 * 3600000).toISOString());
    },
    test: adminOk,
  }),
  adminPost('Allocate to the test agent', '/jobs/{{jobId}}/allocate', { body: { agent_id: '{{agentUserId}}' }, test: adminOk }),
  request('Mint a host token (stand-in issuer)', {
    url: api('/v1/dev/host-token'),
    headers: [APIKEY, JSON_CT],
    auth: bearer('{{adminToken}}'),
    body: { employee_number: '{{agentEmployeeNumber}}' },
    description: 'What a host app (FESS) would hold after its own sign-in. Refused on production.',
    test: function () {
      pm.test('host token minted', () => pm.response.to.have.status(200));
      const b = pm.response.json();
      pm.collectionVariables.set('hostToken', b.token);
      pm.collectionVariables.set('hostTokenIssuedAt', b.issued_at);
    },
  }),
]);

const auth = folder('02 Auth and device', 'The module signs in once with the host token and then owns its session: 15-minute access tokens and a rotating, device-bound refresh token (docs/07 §2, D-32). `POST /v1/device` keeps the device registration current (T2-31).', [
  request('Exchange host token → POS session', {
    url: api('/v1/auth/exchange'),
    headers: [APIKEY, JSON_CT],
    body: {
      issuer: 'pos_dev', token: '{{hostToken}}', issued_at: '{{hostTokenIssuedAt}}',
      device: {
        device_id: '{{deviceId}}', client_type: 'native', platform: 'android', model: 'Postman', os_version: '13', host_app_version: '7.4.0',
        module_version: '{{moduleVersion}}',
        capabilities: { module_version: '{{moduleVersion}}', api_versions: ['1'], spec_versions: ['1.0'], client_type: 'native', platform: 'android' },
      },
      profile: { employee_number: '{{agentEmployeeNumber}}' },
    },
    pre: function () {
      const pos = eval(pm.variables.get('posLib'));
      if (!pm.collectionVariables.get('deviceId')) pm.collectionVariables.set('deviceId', pos.uuidv7());
      pos.need('hostToken', 'run "Mint a host token" in the QA setup folder first');
    },
    test: function () {
      pm.test('POS session issued', () => pm.response.to.have.status(200));
      const s = pm.response.json();
      pm.test('full scope', () => pm.expect(s.scope).to.eql('full'));
      pm.collectionVariables.set('accessToken', s.access_token);
      pm.collectionVariables.set('refreshToken', s.refresh_token);
      pm.collectionVariables.set('sessionId', s.session_id);
    },
  }),
  request('Refresh the session', {
    url: api('/v1/auth/refresh'),
    headers: [APIKEY, JSON_CT],
    body: { refresh_token: '{{refreshToken}}', device_id: '{{deviceId}}' },
    test: function () {
      pm.test('refreshed', () => pm.response.to.have.status(200));
      const s = pm.response.json();
      pm.test('the refresh token rotates', () => pm.expect(s.refresh_token).to.not.eql(pm.collectionVariables.get('refreshToken')));
      pm.collectionVariables.set('accessToken', s.access_token);
      pm.collectionVariables.set('refreshToken', s.refresh_token);
    },
  }),
  agentPost('Update the device (push token)', '/v1/device', {
    body: { push_provider: 'fcm', push_token: 'postman-fcm-{{$timestamp}}', module_version: '{{moduleVersion}}', host_app_version: '7.4.0' },
    description: 'When the host app gets a new push token, or the module or host app is updated. The token itself is never echoed back.',
    test: function () {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const b = pm.response.json();
      pm.test('push registered', () => pm.expect(b.push_registered).to.eql(true));
      pm.test('the token is not echoed', () => pm.expect(b).to.not.have.property('push_token'));
    },
  }),
  agentPost('Unregister push (explicit null)', '/v1/device', {
    body: { push_token: null },
    test: function () {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      pm.test('push unregistered', () => pm.expect(pm.response.json().push_registered).to.eql(false));
    },
  }),
]);

const sync = folder('03 Sync', 'One pull returns everything the phone needs, in pages: jobs, definitions (all kinds), lookup lists, declarations, reason codes, resolved remote config, session tokens, card tokens and home totals (docs/08 §2). With `have`, only what changed comes back.', [
  agentPost('Pull', '/v1/sync/pull', {
    body: { cursors: {}, have: {}, limit: 200 },
    test: function () {
      const pos = eval(pm.variables.get('posLib'));
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const r = pm.response.json();
      const wanted = pm.collectionVariables.get('jobId');
      const job = r.jobs.items.find((j) => (wanted ? j.id === wanted : j.assigned_to_me && ['assigned', 'accepted'].includes(j.status)));
      pm.test('the test job arrives', () => pm.expect(job, 'job ' + (wanted || '(any assigned)')).to.be.ok);
      if (!job) return;
      pm.collectionVariables.set('jobId', job.id);
      const bank = job.bank ? job.bank.id : null;
      const pick = (kind, key) => r.definitions.manifest.find((m) => m.kind === kind && m.key === key && m.context_bank_id === bank)
        || r.definitions.manifest.find((m) => m.kind === kind && m.key === key && m.context_bank_id === null);
      const ref = (kind, key) => {
        const m = pick(kind, key);
        return m ? { version_id: m.version_id, hash: m.definition_hash } : null;
      };
      const decl = (key) => (r.declarations.manifest.find((d) => d.key === key) || {}).id || null;
      const token = r.session_tokens.find((t) => t.job_id === job.id);
      const card = (r.job_cards || []).find((t) => t.job_id === job.id);
      const cfg = (bank && r.config.by_bank[bank]) || r.config.default;
      const ctx = {
        job: {
          id: job.id, reference: job.reference, status: job.status, merchant_name: job.merchant_name, mcc: job.mcc || null, address: job.address,
          attributes: job.attributes || {}, location_type: job.location_type, bank: job.bank, location: job.location, attempts: job.attempts || 0,
        },
        me: r.me,
        totals: r.agent_totals || {},
        defs: {
          form: ref('form', 'site_inspection'), flow: ref('flow', 'site_inspection_flow'), job_schema: ref('job_schema', 'job_attributes'),
          reject: ref('form', 'assignment_reject'), unable: ref('form', 'unable_to_complete'),
        },
        declarations: { agent: decl('agent_declaration'), merchant: decl('merchant_certification') },
        config_version_id: cfg ? cfg.config_version_id : null,
        geofence: cfg && cfg.values ? cfg.values.geofence || null : null,
        token: token ? { id: token.token_id, value: token.token } : null,
        cursors: {},
        have: {
          definition_version_ids: r.definitions.manifest.map((m) => m.version_id),
          declaration_ids: r.declarations.manifest.map((d) => d.id),
          session_token_job_ids: r.session_tokens.map((t) => t.job_id),
          job_card_job_ids: (r.job_cards || []).map((t) => t.job_id),
          agent_card_valid: !!r.agent_card,
        },
      };
      if (r.reason_codes && r.reason_codes.hash) ctx.have.reason_codes_hash = r.reason_codes.hash;
      ['jobs', 'reviews', 'evidence', 'envelopes'].forEach((k) => {
        if (r[k] && r[k].next_cursor) ctx.cursors[k] = r[k].next_cursor;
      });
      pos.setJson('ctx', ctx);
      if (r.agent_card) pm.collectionVariables.set('agentCardToken', r.agent_card.token);
      if (card) pm.collectionVariables.set('jobCardToken', card.token);
      pm.test('a session token for the job (needed to start an inspection)', () => pm.expect(ctx.token).to.be.ok);
      pm.test('inspection definitions resolved for the job', () => pm.expect(ctx.defs.form && ctx.defs.flow).to.be.ok);
      console.log('job ' + job.reference + ' (' + job.status + '), ' + r.definitions.manifest.length + ' active definitions');
    },
  }),
  agentPost('Pull again (only changes)', '/v1/sync/pull', {
    body: '{{pullBody}}',
    pre: function () {
      const pos = eval(pm.variables.get('posLib'));
      const ctx = pos.getJson('ctx', null);
      if (!ctx) throw new Error('Run "Pull" first');
      pm.variables.set('pullBody', JSON.stringify({ cursors: ctx.cursors, have: ctx.have, limit: 200 }));
    },
    test: function () {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const r = pm.response.json();
      pm.test('definition bodies are not re-sent', () => pm.expect(r.definitions.bodies.length).to.eql(0));
      pm.test('session tokens are not re-issued', () => pm.expect(r.session_tokens.length).to.eql(0));
    },
  }),
]);

const needCtx = `const ctx = pos.getJson('ctx', null);
if (!ctx) throw new Error('Run "Pull" first');`;
void needCtx;

const jobEvents = folder('04 Ingest — job events', 'Every device write is an envelope sent to `POST /v1/ingest` (1–50 per request). The server lands it raw before anything else and answers with one receipt per envelope (docs/12 §4–5). Retries are safe: the same envelope id is a duplicate, never a second effect.', [
  ingest('Accept the job', '', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    if (!ctx) throw new Error('Run "Pull" first');
    const env = pos.envelope('job_event', { job_id: ctx.job.id, action: 'accept' });
    pos.setJson('acceptEnvelope', env);
    pos.setIngestBody([env]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed', 'duplicate']);
  }),
  ingest('Re-send the same envelope (idempotent)', 'Same id, same payload: the original receipt comes back as `duplicate`; nothing is applied twice.', function () {
    const pos = eval(pm.variables.get('posLib'));
    const env = pos.getJson('acceptEnvelope', null);
    if (!env) throw new Error('Run "Accept the job" first');
    pos.setIngestBody([env]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    const [r] = pos.checkReceipts(['duplicate']);
    pm.test('the original receipt is returned', () => pm.expect(r.id).to.eql(pos.getJson('acceptEnvelope', {}).id));
  }),
  ingest('Same id, different payload (conflict)', 'Both payloads are kept and an integrity flag is raised for an admin (QA only).', function () {
    const pos = eval(pm.variables.get('posLib'));
    const env = pos.getJson('acceptEnvelope', null);
    if (!env) throw new Error('Run "Accept the job" first');
    const payload = Object.assign({}, env.payload, { note: 'changed after sending (Postman conflict example)' });
    pos.setIngestBody([Object.assign({}, env, { payload, payload_hash: pos.hash(payload) })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['conflict']);
  }),
]);

const inspection = folder('05 Ingest — a complete inspection', 'A full, valid site inspection in the order the module sends it: inspection_started (pins versions, consumes the session token) → traces → evidence_meta → upload grants and uploads → evidence_uploaded → snapshot → sealed submission (docs/12 §6–7, docs/07 §4). The server verifies every photo\'s hash; pg_cron runs the verify worker every 15 s.', [
  ingest('inspection_started', '', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    if (!ctx) throw new Error('Run "Pull" first');
    const start = new Date(Date.now() - 40 * 60000);
    const profile = ctx.job.location_type || 'standalone';
    const p = (ctx.geofence && ctx.geofence.profiles && ctx.geofence.profiles[profile]) || { radius_m: 75, max_accuracy_m: 30, exit_consecutive_fixes: 3, prompt_checkin_on_arrival: false };
    const loc = ctx.job.location || { lat: -26.2385, lng: 27.9087 };
    const near = (x) => Number((x + 0.0001).toFixed(7));
    const relaxed = ['standalone', 'residential'].indexOf(profile) < 0;
    const geofence = {
      profile,
      profile_params: { radius_m: Number(p.radius_m), max_accuracy_m: Number(p.max_accuracy_m), exit_consecutive_fixes: Number(p.exit_consecutive_fixes), prompt_checkin_on_arrival: Boolean(p.prompt_checkin_on_arrival) },
      method: 'inside_fix', passed: true, relaxed, override: false, override_detail: null, job_location: ctx.job.location,
      fix: { lat: near(loc.lat), lng: near(loc.lng), accuracy_m: 12, ts: pos.iso(start), gnss_ts: null, is_mocked: false },
      checkin_fix: null, distance_m: 14, sampled_seconds: 12, config_version_id: ctx.config_version_id, evaluated_at_device: pos.iso(start),
    };
    const integrity = {
      mock_location: false, rooted: false, hooked: false, debugger: false, emulator: false, tampered: false, rasp_provider: 'none',
      attestation: { provider: 'none', verdict: null, obtained_at: null }, clock_offset_ms: 0, checked_at: pos.iso(start),
    };
    const attempt = ctx.job.attempts + 1;
    const context = {
      today: pos.iso(start).slice(0, 10),
      job: { id: ctx.job.id, reference: ctx.job.reference, merchant_name: ctx.job.merchant_name, mcc: ctx.job.mcc, address: ctx.job.address, attributes: ctx.job.attributes, location_type: ctx.job.location_type, bank: ctx.job.bank },
      agent: { id: ctx.me.id, employee_number: ctx.me.employee_number, first_name: ctx.me.first_name, last_name: ctx.me.last_name, attributes: ctx.me.attributes || {} },
      inspection: { attempt, geofence: { inside: true, method: 'inside_fix', profile, relaxed, override: false }, client_type: 'native', started_at: pos.iso(start) },
      stats: ctx.totals,
      previous: null,
    };
    const insp = { id: pos.uuidv7(), attempt, started: pos.iso(start), loc, geofence, integrity, context, evidence: [] };
    pos.setJson('insp', insp);
    pos.setIngestBody([pos.envelope('inspection_started', {
      inspection_id: insp.id, job_id: ctx.job.id, attempt,
      session_token_id: ctx.token ? ctx.token.id : null, session_token: ctx.token ? ctx.token.value : null,
      form_version_id: ctx.defs.form.version_id, definition_hash: ctx.defs.form.hash, flow_version_id: ctx.defs.flow.version_id, flow_hash: ctx.defs.flow.hash,
      job_schema_version_id: ctx.defs.job_schema ? ctx.defs.job_schema.version_id : null, config_version_id: ctx.config_version_id,
      context_snapshot: context, geofence_result: geofence, integrity, started_at_device: insp.started, clock_offset_ms: 0,
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  ingest('traces_batch', 'Breadcrumbs sampled on site (docs/07 §7).', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    const insp = pos.getJson('insp', null);
    if (!ctx || !insp) throw new Error('Run "inspection_started" first');
    const t0 = Date.parse(insp.started);
    const fixes = [0, 1, 2, 3, 4, 5].map((i) => {
      const at = new Date(t0 + i * 5 * 60000);
      return {
        fix_id: pos.uuidv7(), ts_device: pos.iso(at), ts_monotonic_ms: 10000 + i * 300000, gnss_ts: null,
        lat: Number((insp.loc.lat + 0.00005 * i).toFixed(7)), lng: Number((insp.loc.lng + 0.00005).toFixed(7)),
        accuracy_m: 10, speed: 0, is_mocked: false, inside_fence: true, event: i === 0 ? 'enter' : 'fix',
      };
    });
    insp.lastTraceAt = fixes[fixes.length - 1].ts_device;
    pos.setJson('insp', insp);
    pos.setIngestBody([pos.envelope('traces_batch', { inspection_id: insp.id, job_id: ctx.job.id, batch_seq: 0, fixes })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  ingest('evidence_meta ×5 (2 external, 2 internal, signature)', 'Each capture is described (hash of the exact bytes) before its bytes upload. The "photos" here are small text files labelled image/jpeg: the server verifies the hash of the stored bytes, not the image format.', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    const insp = pos.getJson('insp', null);
    if (!ctx || !insp) throw new Error('Run "inspection_started" first');
    const specs = [['external_photos', 'external', 'photo'], ['external_photos', 'external', 'photo'], ['internal_photos', 'internal', 'photo'],
      ['internal_photos', 'internal', 'photo'], ['interviewee_signature', 'signature', 'signature']];
    insp.evidence = specs.map((s, i) => {
      const content = 'fess-pos postman evidence | ' + s[0] + ' ' + (i + 1) + ' | ' + pos.uuidv7();
      return { id: pos.uuidv7(), field_key: s[0], category: s[1], type: s[2], content, sha256: pos.sha256(content), bytes: content.length };
    });
    pos.setJson('insp', insp);
    const t0 = Date.parse(insp.started);
    pos.setIngestBody(insp.evidence.map((c, i) => pos.envelope('evidence_meta', {
      evidence_id: c.id, inspection_id: insp.id, job_id: ctx.job.id, session_token_id: ctx.token ? ctx.token.id : null,
      field_key: c.field_key, category: c.category, type: c.type, sha256: c.sha256, bytes: c.bytes, mime: 'image/jpeg', width: 1, height: 1,
      captured_at_device: pos.iso(new Date(t0 + (5 + i) * 60000)), captured_at_monotonic_ms: 60000 * (5 + i), gnss_time: null,
      location: { lat: insp.loc.lat, lng: insp.loc.lng }, accuracy_m: 9, is_mocked: false,
    })));
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  agentPost('Upload grant (first photo)', '/v1/evidence/upload-grant', {
    body: { evidence_id: '{{evidenceId}}' },
    description: 'The server checks ownership and derives the storage path; the object can never be overwritten. `resumable` is the TUS endpoint for large files.',
    pre: function () {
      const pos = eval(pm.variables.get('posLib'));
      const insp = pos.getJson('insp', null);
      if (!insp || !insp.evidence.length) throw new Error('Run "evidence_meta" first');
      pm.variables.set('evidenceId', insp.evidence[0].id);
    },
    test: function () {
      const pos = eval(pm.variables.get('posLib'));
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const g = pm.response.json();
      pm.test('an upload target is issued', () => pm.expect(g.state).to.eql('upload'));
      pm.collectionVariables.set('uploadUrl', g.signed_url || '');
      pm.collectionVariables.set('uploadContent', pos.getJson('insp', { evidence: [{}] }).evidence[0].content || '');
    },
  }),
  request('Upload the photo bytes (signed URL)', {
    method: 'PUT',
    url: '{{uploadUrl}}',
    headers: [APIKEY, { key: 'authorization', value: 'Bearer {{publishableKey}}', type: 'text' }, { key: 'content-type', value: 'image/jpeg', type: 'text' }, { key: 'x-upsert', value: 'false', type: 'text' }],
    body: '{{uploadContent}}',
    language: 'text',
    description: 'Straight to Supabase Storage with the one-time signed URL from the grant.',
    test: function () {
      pm.test('stored', () => pm.expect(pm.response.code).to.be.oneOf([200, 201]));
    },
  }),
  ingest('evidence_uploaded ×5 (uploads the other four first)', 'The pre-request script gets a grant and uploads the bytes for the remaining four items, then sends evidence_uploaded for all five. The server queues hash verification in the same transaction.', function () {
    const pos = eval(pm.variables.get('posLib'));
    const insp = pos.getJson('insp', null);
    if (!insp || !insp.evidence.length) throw new Error('Run "evidence_meta" first');
    const base = pm.environment.get('apiBaseUrl');
    const key = pm.environment.get('publishableKey');
    const token = pm.collectionVariables.get('accessToken');
    const rest = insp.evidence.slice(1);
    function finish() {
      const at = pos.iso();
      pos.setIngestBody(insp.evidence.map((c) => pos.envelope('evidence_uploaded', { evidence_id: c.id, sha256: c.sha256, bytes: c.bytes, uploaded_at_device: at })));
    }
    function next(i) {
      if (i >= rest.length) return finish();
      const c = rest[i];
      pm.sendRequest({
        url: base + '/v1/evidence/upload-grant',
        method: 'POST',
        header: [{ key: 'apikey', value: key }, { key: 'authorization', value: 'Bearer ' + token }, { key: 'content-type', value: 'application/json' }],
        body: { mode: 'raw', raw: JSON.stringify({ evidence_id: c.id }) },
      }, (err, res) => {
        if (err) throw err;
        const g = res.json();
        if (g.state !== 'upload') return next(i + 1);
        pm.sendRequest({
          url: g.signed_url,
          method: 'PUT',
          header: [{ key: 'apikey', value: key }, { key: 'authorization', value: 'Bearer ' + key }, { key: 'content-type', value: 'image/jpeg' }, { key: 'x-upsert', value: 'false' }],
          body: { mode: 'raw', raw: c.content },
        }, (err2, res2) => {
          if (err2) throw err2;
          if (res2.code >= 300) throw new Error('upload failed for ' + c.field_key + ': HTTP ' + res2.code + ' ' + res2.text());
          next(i + 1);
        });
      });
    }
    next(0);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  ingest('inspection_snapshot', 'Optional in-progress answers, so an admin can see work before it is submitted. Last writer wins by device_seq (docs/12 §15).', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    const insp = pos.getJson('insp', null);
    if (!ctx || !insp) throw new Error('Run the inspection requests in order first');
    const built = pos.answersFor(ctx, insp);
    pos.setIngestBody([pos.envelope('inspection_snapshot', {
      inspection_id: insp.id, job_id: ctx.job.id, attempt: insp.attempt, answers: built.answers, current_step: 'review',
      snapshot_at_device: pos.iso(new Date(built.end.getTime() - 2 * 60000)),
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  ingest('submission (sealed)', 'Self-sufficient and sealed by the submission hash: answers hash, sorted evidence hashes, session token, start and submit times and device id (schema/api/README).', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    const insp = pos.getJson('insp', null);
    if (!ctx || !insp || !insp.evidence.length) throw new Error('Run the inspection requests in order first');
    const built = pos.answersFor(ctx, insp);
    const answersHash = pos.hash(built.answers);
    const items = insp.evidence.map((c) => ({ evidence_id: c.id, field_key: c.field_key, category: c.category, sha256: c.sha256, bytes: c.bytes }));
    const submitted = pos.iso(built.end);
    const tokenId = ctx.token ? ctx.token.id : null;
    const submissionHash = pos.sha256(pos.canonical(['fess-pos/submission-hash/v1', answersHash, items.map((i) => i.sha256).sort(), tokenId,
      insp.started, submitted, pm.collectionVariables.get('deviceId')]));
    pos.setIngestBody([pos.envelope('submission', {
      inspection_id: insp.id, job_id: ctx.job.id, attempt: insp.attempt,
      definition_refs: { form: ctx.defs.form, flow: ctx.defs.flow, job_schema: ctx.defs.job_schema },
      config_version_id: ctx.config_version_id, context_snapshot: insp.context, answers: built.answers, answers_hash: answersHash,
      manifest: { items, trace_batch_count: 1, last_trace_at: insp.lastTraceAt || insp.started },
      session_token_id: tokenId, session_token: ctx.token ? ctx.token.value : null,
      geofence: insp.geofence, integrity: Object.assign({}, insp.integrity, { checked_at: submitted }),
      diagnostics: { module_version: pm.environment.get('moduleVersion') || '0.1.0', platform: 'android', host_app_version: '7.4.0', os_version: '13', model: 'Postman', free_storage_mb: 2048, battery_restricted: false, network: 'wifi' },
      submission_hash: submissionHash, started_at_device: insp.started, submitted_at_device: submitted, clock_offset_ms: 0,
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    const [r] = pos.checkReceipts(['committed']);
    if (r && r.result) {
      pm.test('inspection ' + r.result.inspection_status + ' (' + r.result.evidence_verified + '/' + r.result.evidence_expected + ' photos verified so far)', () =>
        pm.expect(['submitted', 'verifying', 'under_review']).to.include(r.result.inspection_status));
    }
  }),
  agentPost('Pull (evidence status)', '/v1/sync/pull', {
    body: '{{pullBody}}',
    description: 'The phone learns each photo\'s state from pulls: uploaded → verified (then it may delete its local copy, docs/08 §4). Verification runs every 15 s, so run this again after a little while.',
    pre: function () {
      const pos = eval(pm.variables.get('posLib'));
      const ctx = pos.getJson('ctx', null);
      if (!ctx) throw new Error('Run "Pull" first');
      pm.variables.set('pullBody', JSON.stringify({ cursors: {}, have: ctx.have, limit: 200 }));
    },
    test: function () {
      const pos = eval(pm.variables.get('posLib'));
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const ours = pos.getJson('insp', { evidence: [] }).evidence.map((c) => c.id);
      const states = pm.response.json().evidence.items.filter((e) => ours.indexOf(e.id) >= 0).map((e) => e.upload_state);
      console.log('evidence states: ' + (states.join(', ') || '(none yet)'));
      pm.test('every photo reported', () => pm.expect(states.length).to.eql(ours.length));
    },
  }),
]);

const otherTypes = folder('06 Ingest — other envelope types', 'Device reports and records that ride the same outbox.', [
  ingest('sync_report', 'Backlog, storage, battery restriction and capabilities (docs/12 §9); drives the custody dashboard.', function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.setIngestBody([pos.envelope('sync_report', {
      reported_at_device: pos.iso(), pending: { submission: 0, evidence: 0 }, oldest_pending_at: null, last_success_at: pos.iso(),
      free_storage_mb: 2048, battery_restricted: false, module_version: pm.environment.get('moduleVersion') || '0.1.0', config_version_id: null,
      capabilities: { spec_versions: ['1.0'] },
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  ingest('custody_batch', 'Device-side chain-of-custody events (docs/12 §10).', function () {
    const pos = eval(pm.variables.get('posLib'));
    const insp = pos.getJson('insp', null);
    if (!insp) throw new Error('Run "inspection_started" first');
    pos.setIngestBody([pos.envelope('custody_batch', {
      events: [{ subject_type: 'inspection', subject_id: insp.id, event: 'receipt_received', at_device: pos.iso(), monotonic_ms: 999999 }],
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  ingest('client_error', 'Parked items and recovery anomalies the device reports (docs/12 §4).', function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.setIngestBody([pos.envelope('client_error', {
      errors: [{ code: 'POSTMAN_EXAMPLE', kind: 'other', about_envelope_id: null, message: 'Example client error sent from Postman', detail: { source: 'postman' }, at: pos.iso() }],
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
  ingest('form_submission (generic form page)', 'A generic `record.submit` form (docs/04 §3.6), here the seeded reason form against the job. Known gap (T3-20): form_submission validation does not yet load `options_source` reason codes, so this comes back `rejected` (INVALID_OPTION). The data is still landed and kept, which is what the test checks.', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    const insp = pos.getJson('insp', null);
    if (!ctx || !insp || !ctx.defs.reject) throw new Error('Run "Pull" and "inspection_started" first');
    const answers = { reason_code: { v: 'too_far' }, note: { v: 'Postman record.submit example' } };
    pos.setIngestBody([pos.envelope('form_submission', {
      form_submission_id: pos.uuidv7(), form_version_id: ctx.defs.reject.version_id, definition_hash: ctx.defs.reject.hash,
      subject_type: 'job', subject_id: ctx.job.id, config_version_id: ctx.config_version_id, context_snapshot: insp.context,
      answers, answers_hash: pos.hash(answers), submitted_at_device: pos.iso(),
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts();
  }),
]);

const verifyTest = function () {
  pm.test('HTTP 200', () => pm.response.to.have.status(200));
  const b = pm.response.json();
  pm.test('card is valid', () => pm.expect(b.status).to.eql('valid'));
  pm.test('employee number is masked', () => pm.expect(b.agent.employee_number_masked).to.match(/^•+.{3}$/));
  pm.test('a ' + kind, () => pm.expect(b.kind).to.eql(kind));
};
const publicVerify = folder('07 Public card verification', 'What a merchant\'s phone sees after scanning an authorisation-card QR (docs/07 §10). No key needed. The same URL returns a web page for browsers.', [
  request('Verify the agent card (JSON)', {
    method: 'GET', url: api('/v1/public/verify/{{agentCardToken}}'), headers: [{ key: 'accept', value: 'application/json', type: 'text' }],
    test: verifyTest,
    testVars: { kind: 'agent_card' },
  }),
  request('Verify the job card (JSON)', {
    method: 'GET', url: api('/v1/public/verify/{{jobCardToken}}'), headers: [{ key: 'accept', value: 'application/json', type: 'text' }],
    test: verifyTest,
    testVars: { kind: 'job_card' },
  }),
  request('Verify the agent card (web page)', {
    method: 'GET', url: api('/v1/public/verify/{{agentCardToken}}'), headers: [{ key: 'accept', value: 'text/html', type: 'text' }],
    description: 'Known issue (docs/10 R-40, T2-32): on *.supabase.co, Supabase serves edge-function HTML as text/plain, so browsers show the markup as text.',
    test: function () {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      pm.test('returns the verification page markup', () => pm.expect(pm.response.text()).to.include('<html'));
      const type = pm.response.headers.get('content-type') || '';
      if (type.indexOf('text/html') < 0) {
        console.warn('Served as ' + type + ': browsers will show the markup as text. Supabase serves edge-function HTML as text/plain on *.supabase.co (docs/10 R-40, T2-32).');
      }
    },
  }),
]);

const alternatives = folder('08 Other agent actions (best on a fresh job)', 'Decline and unable-to-complete use the bank\'s configurable reason forms (docs/06 §3). On a job that is already accepted or submitted, the server records them with its verdict instead of applying them, and nothing is dropped (docs/08 §6). For a clean run, do "01 QA setup" and "Pull" again first.', [
  ingest('Decline the job (reason form)', '', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    if (!ctx || !ctx.defs.reject) throw new Error('Run "Pull" first');
    const answers = { reason_code: { v: 'too_far' }, note: { v: 'Covering another area this week (Postman example)' } };
    pos.setIngestBody([pos.envelope('job_event', {
      job_id: ctx.job.id, action: 'reject', trigger: 'agent', reason_code: 'too_far', note: 'Covering another area this week (Postman example)',
      form_version_id: ctx.defs.reject.version_id, definition_hash: ctx.defs.reject.hash, form_answers: answers, answers_hash: pos.hash(answers),
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts();
  }),
  ingest('Unable to complete (reason form)', '', function () {
    const pos = eval(pm.variables.get('posLib'));
    const ctx = pos.getJson('ctx', null);
    if (!ctx || !ctx.defs.unable) throw new Error('Run "Pull" first');
    const answers = { reason_code: { v: 'business_closed' }, note: { v: 'Shutters down on arrival (Postman example)' } };
    pos.setIngestBody([pos.envelope('job_event', {
      job_id: ctx.job.id, action: 'unable', trigger: 'agent', reason_code: 'business_closed', note: 'Shutters down on arrival (Postman example)',
      form_version_id: ctx.defs.unable.version_id, definition_hash: ctx.defs.unable.hash, form_answers: answers, answers_hash: pos.hash(answers),
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts();
  }),
]);

const errorCases = folder('09 Error cases', 'Every API error has the same shape: `{error: {code, message, retryable, details?}, request_id}`. `retryable` tells the module whether to back off and retry or park the item (docs/12 §4).', [
  request('No publishable key → 401', {
    url: api('/v1/sync/pull'), headers: [JSON_CT], auth: bearer('{{accessToken}}'), body: { cursors: {}, have: {} },
    test: function () {
      eval(pm.variables.get('posLib')).checkError(401, 'UNAUTHENTICATED');
    },
  }),
  request('Forged host token → 401', {
    url: api('/v1/auth/exchange'), headers: [APIKEY, JSON_CT],
    body: { issuer: 'pos_dev', token: 'not-a-real-host-token', device: { device_id: '{{deviceId}}' } },
    test: function () {
      eval(pm.variables.get('posLib')).checkError(401, 'INVALID_HOST_TOKEN');
    },
  }),
  request('Invalid access token → 401', {
    url: api('/v1/sync/pull'), headers: [APIKEY, JSON_CT], auth: bearer('not-a-token'), body: { cursors: {}, have: {} },
    test: function () {
      eval(pm.variables.get('posLib')).checkError(401, 'UNAUTHENTICATED');
    },
  }),
  request('Invalid request body → 400', {
    url: api('/v1/device'), headers: [APIKEY, JSON_CT], auth: bearer('{{accessToken}}'), body: { push_token: 'token-without-provider' },
    test: function () {
      eval(pm.variables.get('posLib')).checkError(400, 'INVALID_REQUEST');
    },
  }),
  request('Unknown endpoint → 404', {
    method: 'GET', url: api('/v1/no-such-endpoint'),
    test: function () {
      eval(pm.variables.get('posLib')).checkError(404, 'NOT_FOUND');
    },
  }),
]);

const signOut = folder('10 Sign out', 'Sign-out ends UI access but not custody: the session drops to `ingest_only`, so queued work still uploads (docs/03 §3).', [
  agentPost('Sign out (→ ingest_only)', '/v1/auth/signout', {
    body: {},
    test: function () {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      pm.test('ingest_only', () => pm.expect(pm.response.json().scope).to.eql('ingest_only'));
    },
  }),
  request('Refresh after sign-out', {
    url: api('/v1/auth/refresh'), headers: [APIKEY, JSON_CT], body: { refresh_token: '{{refreshToken}}', device_id: '{{deviceId}}' },
    test: function () {
      pm.test('HTTP 200', () => pm.response.to.have.status(200));
      const s = pm.response.json();
      pm.test('still ingest_only', () => pm.expect(s.scope).to.eql('ingest_only'));
      pm.collectionVariables.set('accessToken', s.access_token);
      pm.collectionVariables.set('refreshToken', s.refresh_token);
    },
  }),
  agentPost('Pull after sign-out → 403', '/v1/sync/pull', {
    body: { cursors: {}, have: {} },
    test: function () {
      eval(pm.variables.get('posLib')).checkError(403, 'SCOPE_INSUFFICIENT');
    },
  }),
  ingest('Uploads still land after sign-out', '', function () {
    const pos = eval(pm.variables.get('posLib'));
    const insp = pos.getJson('insp', null);
    if (!insp) throw new Error('Run "inspection_started" first');
    pos.setIngestBody([pos.envelope('custody_batch', {
      events: [{ subject_type: 'inspection', subject_id: insp.id, event: 'local_bytes_deleted', at_device: pos.iso(), monotonic_ms: 1999999 }],
    })]);
  }, function () {
    const pos = eval(pm.variables.get('posLib'));
    pos.checkReceipts(['committed']);
  }),
]);

const RUNTIME = ['deviceId', 'deviceSeq', 'monotonicMs', 'accessToken', 'refreshToken', 'sessionId', 'hostToken', 'hostTokenIssuedAt',
  'adminAal1Token', 'adminFactorId', 'adminToken', 'jobId', 'jobReference', 'ctx', 'insp', 'acceptEnvelope', 'lastEnvelopes',
  'agentCardToken', 'jobCardToken', 'uploadUrl', 'uploadContent'];

const collection = {
  info: {
    _postman_id: '6f3c9d52-6b1e-4d8a-9a1f-2f5e0c7b4e11',
    name: 'FESS POS — Module API (v1)',
    description: [
      'The POS API the fess_pos module calls (docs/03 §4, docs/08, docs/12). Generated by `fess-pos/tools/postman/build.mjs` — edit it there.',
      '',
      '**Environments.** Pick "FESS POS — QA" or "FESS POS — production". Production is **read-only** here: every non-GET request is',
      'skipped (instructions §10–11: no test data on production). QA uses dedicated test users; `tools/postman/provision-qa.ts`',
      'creates them and writes a ready QA environment to `~/.fess-pos/postman/`.',
      '',
      '**Order.** Run the folders top to bottom (or run the whole collection): QA setup → exchange → pull → job events → a complete',
      'inspection → other types → card verification → other actions → error cases → sign out. Each request stores what the next',
      'one needs in collection variables. Envelope ids, hashes (RFC 8785 JCS + SHA-256) and device sequence numbers are computed',
      'by the scripts, exactly as the module computes them.',
    ].join('\n'),
    schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
  },
  event: [{ listen: 'prerequest', script: { type: 'text/javascript', exec: lines(collectionPre) } }],
  variable: RUNTIME.map((key) => ({ key, value: '', type: 'string' })),
  item: [health, setup, auth, sync, jobEvents, inspection, otherTypes, publicVerify, alternatives, errorCases, signOut],
};

function environment(name, values) {
  return {
    id: name === 'qa' ? 'b4b3f0a1-1c2d-4e5f-8a9b-0c1d2e3f4a51' : 'b4b3f0a1-1c2d-4e5f-8a9b-0c1d2e3f4a52',
    name: name === 'qa' ? 'FESS POS — QA' : 'FESS POS — production',
    values: values.map(([key, value, type = 'default']) => ({ key, value, type, enabled: true })),
    _postman_variable_scope: 'environment',
  };
}
const base = (env) => [
  ['env', env],
  ['supabaseUrl', `https://${REFS[env]}.supabase.co`],
  ['apiBaseUrl', `https://${REFS[env]}.supabase.co/functions/v1/api`],
  ['publishableKey', ''],
  ['moduleVersion', '0.1.0'],
];
const qaEnv = environment('qa', [
  ...base('qa'),
  ['adminEmail', 'api.tester@fess-pos.test'],
  ['adminPassword', '', 'secret'],
  ['adminTotpSecret', '', 'secret'],
  ['testBankId', ''],
  ['agentEmployeeNumber', 'API-AG01'],
  ['agentUserId', ''],
  ['agent2EmployeeNumber', 'API-AG02'],
  ['agent2UserId', ''],
]);
const prodEnv = environment('production', base('production'));

const write = (file, value) => writeFileSync(join(here, file), `${JSON.stringify(value, null, 2)}\n`);
write('fess-pos-module-api.postman_collection.json', collection);
write('fess-pos-qa.postman_environment.json', qaEnv);
write('fess-pos-production.postman_environment.json', prodEnv);
const count = (items) => items.reduce((n, i) => n + (i.item ? count(i.item) : 1), 0);
console.log(`Wrote the collection (${count(collection.item)} requests) and the QA and production environment templates to ${here}`);
