// GENERATED by tool/generate_config_defaults.dart from
// schema/config/. Do not edit by hand.

import 'package:fess_pos/src/core/config/config_leaf.dart';

/// The bundled safe defaults (schema/config/defaults.json,
/// docs/13 §5): behaviour only, never endpoints or secrets.
const Map<String, Object?> bundledConfigDefaults = <String, Object?>{
  'maps': <String, Object?>{
    'tile_url': null,
    'api_key': null,
    'prefetch_zoom': <Object?>[14, 17],
    'wifi_only_prefetch': false,
  },
  'observability': <String, Object?>{'sentry_dsn': null, 'sample_rate': 0.2},
  'geofence': <String, Object?>{
    'sample_seconds': 60,
    'trace_interval_s': 20,
    'outside_fix': <String, Object?>{
      'allowed': true,
      'max_accuracy_m': 30,
      'valid_minutes': 20,
    },
    'override_radius_multiplier': 2,
    'override_max_m': 500,
    'default_profile': 'standalone',
    'profiles': <String, Object?>{
      'standalone': <String, Object?>{
        'radius_m': 75,
        'max_accuracy_m': 30,
        'exit_consecutive_fixes': 3,
        'prompt_checkin_on_arrival': false,
      },
      'residential': <String, Object?>{
        'radius_m': 75,
        'max_accuracy_m': 30,
        'exit_consecutive_fixes': 3,
        'prompt_checkin_on_arrival': false,
      },
      'shopping_centre': <String, Object?>{
        'radius_m': 250,
        'max_accuracy_m': 75,
        'exit_consecutive_fixes': 5,
        'prompt_checkin_on_arrival': true,
      },
      'office_park': <String, Object?>{
        'radius_m': 200,
        'max_accuracy_m': 75,
        'exit_consecutive_fixes': 5,
        'prompt_checkin_on_arrival': true,
      },
      'large_site': <String, Object?>{
        'radius_m': 300,
        'max_accuracy_m': 75,
        'exit_consecutive_fixes': 5,
        'prompt_checkin_on_arrival': false,
      },
    },
  },
  'integrity': <String, Object?>{
    'block_on_mock': true,
    'block_on_root': true,
    'attestation_max_age_h': 24,
  },
  'photos': <String, Object?>{'max_long_edge_px': 2048, 'jpeg_quality': 80},
  'auth': <String, Object?>{
    'reverify_hours': 24,
    'max_host_token_age_h': 696,
    'access_token_ttl_s': 900,
    'refresh_token_ttl_days': 30,
  },
  'sync': <String, Object?>{
    'foreground_interval_s': 60,
    'idle_interval_s': 900,
    'retain_committed_payload_days': 30,
  },
  'storage': <String, Object?>{
    'cap_mb': 500,
    'block_new_work_at_pct': 80,
    'tile_cache_mb': 150,
  },
  'min_module_version': <String, Object?>{
    'nag': '0.0.0',
    'new_work': '0.0.0',
    'block_in_progress': '0.0.0',
  },
  'features': <String, Object?>{
    'repeatable_groups': true,
    'inspection_snapshots': true,
  },
  'client_mode': 'native',
  'pos': <String, Object?>{'enabled': true},
  'inspections': <String, Object?>{'start_enabled': true},
  'governance': <String, Object?>{'four_eyes_global': false},
  'assignment': <String, Object?>{'response_timeout_h': 24},
  'agent_card': <String, Object?>{'token_ttl_h': 24},
  'session_tokens': <String, Object?>{'window_padding_h': 24},
  'locale': <String, Object?>{'timezone': 'Africa/Johannesburg'},
  'theme': <String, Object?>{'primary_color': null, 'font_family': null},
};

/// Every key: its type and bounds
/// (schema/config/remote-config.schema.json).
const Map<String, ConfigLeaf> configLeaves = {
  'maps.tile_url': ConfigLeaf(ConfigType.string, nullable: true),
  'maps.api_key': ConfigLeaf(ConfigType.string, nullable: true),
  'maps.prefetch_zoom': ConfigLeaf(ConfigType.array),
  'maps.wifi_only_prefetch': ConfigLeaf(ConfigType.boolean),
  'observability.sentry_dsn': ConfigLeaf(ConfigType.string, nullable: true),
  'observability.sample_rate': ConfigLeaf(ConfigType.number, min: 0, max: 1),
  'geofence.sample_seconds': ConfigLeaf(ConfigType.integer, min: 10, max: 180),
  'geofence.trace_interval_s': ConfigLeaf(ConfigType.integer, min: 5, max: 120),
  'geofence.outside_fix.allowed': ConfigLeaf(ConfigType.boolean),
  'geofence.outside_fix.max_accuracy_m': ConfigLeaf(
    ConfigType.integer,
    min: 5,
    max: 100,
  ),
  'geofence.outside_fix.valid_minutes': ConfigLeaf(
    ConfigType.integer,
    min: 1,
    max: 120,
  ),
  'geofence.override_radius_multiplier': ConfigLeaf(
    ConfigType.number,
    min: 1,
    max: 3,
  ),
  'geofence.override_max_m': ConfigLeaf(ConfigType.integer, min: 25, max: 500),
  'geofence.default_profile': ConfigLeaf(ConfigType.string),
  'geofence.profiles': ConfigLeaf(ConfigType.object),
  'integrity.block_on_mock': ConfigLeaf(ConfigType.boolean),
  'integrity.block_on_root': ConfigLeaf(ConfigType.boolean),
  'integrity.attestation_max_age_h': ConfigLeaf(
    ConfigType.integer,
    min: 1,
    max: 168,
  ),
  'photos.max_long_edge_px': ConfigLeaf(
    ConfigType.integer,
    min: 1024,
    max: 4096,
  ),
  'photos.jpeg_quality': ConfigLeaf(ConfigType.integer, min: 50, max: 95),
  'auth.reverify_hours': ConfigLeaf(ConfigType.integer, min: 1, max: 168),
  'auth.max_host_token_age_h': ConfigLeaf(
    ConfigType.integer,
    min: 1,
    max: 2160,
  ),
  'auth.access_token_ttl_s': ConfigLeaf(
    ConfigType.integer,
    min: 300,
    max: 3600,
  ),
  'auth.refresh_token_ttl_days': ConfigLeaf(
    ConfigType.integer,
    min: 1,
    max: 90,
  ),
  'sync.foreground_interval_s': ConfigLeaf(
    ConfigType.integer,
    min: 15,
    max: 600,
  ),
  'sync.idle_interval_s': ConfigLeaf(ConfigType.integer, min: 900, max: 86400),
  'sync.retain_committed_payload_days': ConfigLeaf(
    ConfigType.integer,
    min: 7,
    max: 365,
  ),
  'storage.cap_mb': ConfigLeaf(ConfigType.integer, min: 100, max: 4096),
  'storage.block_new_work_at_pct': ConfigLeaf(
    ConfigType.integer,
    min: 50,
    max: 95,
  ),
  'storage.tile_cache_mb': ConfigLeaf(ConfigType.integer, min: 0, max: 1024),
  'min_module_version.nag': ConfigLeaf(ConfigType.string),
  'min_module_version.new_work': ConfigLeaf(ConfigType.string),
  'min_module_version.block_in_progress': ConfigLeaf(ConfigType.string),
  'features': ConfigLeaf(ConfigType.object),
  'client_mode': ConfigLeaf(ConfigType.string, values: ['native', 'web']),
  'pos.enabled': ConfigLeaf(ConfigType.boolean),
  'inspections.start_enabled': ConfigLeaf(ConfigType.boolean),
  'governance.four_eyes_global': ConfigLeaf(ConfigType.boolean),
  'assignment.response_timeout_h': ConfigLeaf(
    ConfigType.integer,
    min: 1,
    max: 168,
  ),
  'agent_card.token_ttl_h': ConfigLeaf(ConfigType.integer, min: 1, max: 72),
  'session_tokens.window_padding_h': ConfigLeaf(
    ConfigType.integer,
    min: 0,
    max: 72,
  ),
  'locale.timezone': ConfigLeaf(ConfigType.string),
  'theme.primary_color': ConfigLeaf(ConfigType.string, nullable: true),
  'theme.font_family': ConfigLeaf(ConfigType.string, nullable: true),
};
