// dart format width=80
// Generated by `dart run drift_dev make-migrations`, then filled in: every
// schema step is checked against the dumps in drift_schemas/, and existing
// rows must survive each step.
@TestOn('vm')
library;

import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:fess_pos/src/data/local/pos_database.dart';
import 'package:flutter_test/flutter_test.dart';

import 'generated/schema.dart';
import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('every schema step', () {
    const versions = GeneratedHelper.versions;
    for (final (i, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(i + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final db = PosDatabase(schema.newConnection());
            await verifier.migrateAndValidate(db, toVersion);
            await db.close();
          });
        }
      });
    }
  });

  test('1 → 2 (the outbox) keeps every existing row', () async {
    const at = '2026-09-13T10:00:00.000+02:00';
    const quarantined = '[{"name":"fess_pos-20260913T080000Z.db","at":"$at"}]';
    await verifier.testWithDataIntegrity(
      oldVersion: 1,
      newVersion: 2,
      createOld: v1.DatabaseAtV1.new,
      createNew: v2.DatabaseAtV2.new,
      openTestedDatabase: PosDatabase.new,
      createItems: (batch, oldDb) {
        batch
          ..insertAll(oldDb.moduleMeta, [
            const v1.ModuleMetaData(
              key: 'store_created_at',
              value: at,
              updatedAt: at,
            ),
            const v1.ModuleMetaData(
              key: 'quarantined_stores',
              value: quarantined,
              updatedAt: at,
            ),
          ])
          ..insertAll(oldDb.syncState, [
            const v1.SyncStateData(
              key: 'cursor.jobs',
              value: 'c1',
              updatedAt: at,
            ),
          ]);
      },
      validateItems: (newDb) async {
        expect(await newDb.select(newDb.moduleMeta).get(), [
          const v2.ModuleMetaData(
            key: 'store_created_at',
            value: at,
            updatedAt: at,
          ),
          const v2.ModuleMetaData(
            key: 'quarantined_stores',
            value: quarantined,
            updatedAt: at,
          ),
        ]);
        expect(await newDb.select(newDb.syncState).get(), [
          const v2.SyncStateData(
            key: 'cursor.jobs',
            value: 'c1',
            updatedAt: at,
          ),
        ]);
        expect(await newDb.select(newDb.outbox).get(), isEmpty);
      },
    );
  });
}
