// Plain-language names, descriptions and icons for the engine catalogues (docs/11), used by the structured editors and
// the component pickers. The catalogues themselves (types, props, rule-ability) come from the engine; this file only
// adds wording, so a new component still appears (with a humanised name) before anyone writes copy for it.
import {
  AlignLeft,
  AtSign,
  Badge as BadgeIcon,
  BarChart3,
  Calendar,
  CalendarClock,
  CheckSquare,
  CircleDot,
  ClipboardCheck,
  Clock,
  Columns3,
  Contact,
  CreditCard,
  FileSignature,
  FileText,
  Fingerprint,
  Flag,
  Hash,
  Heading1,
  IdCard,
  Image,
  Info,
  LayoutList,
  List,
  ListChecks,
  type LucideIcon,
  MapPin,
  Megaphone,
  MessageSquareWarning,
  Minus,
  MousePointerClick,
  Navigation,
  Percent,
  PenLine,
  Phone,
  Camera,
  Receipt,
  RefreshCw,
  Repeat,
  Search,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Square,
  Star,
  Tag,
  TextCursorInput,
  ToggleLeft,
  Type,
  UserRound,
  Wallet,
  Hourglass,
  Building2,
  Calculator,
  Link2,
  PanelTop,
  ScrollText,
  Workflow,
  Map as MapIcon,
} from 'lucide-react';
import { humanLabel } from '@/components/structured-view';
import type { ComponentCategory } from '@/lib/engine';

export interface Wording {
  name: string;
  description: string;
  icon: LucideIcon;
}

export const CATEGORY_LABEL: Record<ComponentCategory, string> = {
  text: 'Text and numbers',
  choice: 'Choices',
  date: 'Dates and times',
  location: 'Location',
  evidence: 'Photos and signatures',
  legal: 'Declarations and consent',
  display: 'Information for the agent',
  computed: 'Filled in automatically',
  structural: 'Layout and repeating groups',
};

export const CATEGORY_ORDER: ComponentCategory[] = ['text', 'choice', 'date', 'location', 'evidence', 'legal', 'display', 'computed', 'structural'];

const COMPONENT_WORDING: Record<string, Wording> = {
  text: { name: 'Short text', description: 'A single line of text, such as a name.', icon: TextCursorInput },
  textarea: { name: 'Long text', description: 'Several lines of text, such as a description or a note.', icon: AlignLeft },
  number: { name: 'Number', description: 'A number, optionally with a unit such as m² or days.', icon: Hash },
  percentage: { name: 'Percentage', description: 'A number from 0 to 100.', icon: Percent },
  phone: { name: 'Phone number', description: 'A South African (or other) phone number, checked for format.', icon: Phone },
  currency: { name: 'Amount of money', description: 'An amount in rand (or another currency).', icon: Wallet },
  slider: { name: 'Slider', description: 'Pick a number by sliding between two ends.', icon: SlidersHorizontal },
  rating: { name: 'Rating', description: 'Stars or a numbered scale.', icon: Star },
  email: { name: 'Email address', description: 'An email address, checked for format.', icon: AtSign },
  id_number: { name: 'ID number', description: 'A South African ID or passport number, checked for format.', icon: IdCard },
  registration_number: { name: 'Company registration number', description: 'A CIPC or VAT number, checked for format.', icon: Building2 },
  boolean: { name: 'Yes / No', description: 'A question answered Yes or No.', icon: ToggleLeft },
  tri_state: { name: 'Yes / No / Not applicable', description: 'Yes, No or N/A.', icon: CircleDot },
  single_select: { name: 'Pick one', description: 'Choose one answer from a list (radio buttons, dropdown or chips).', icon: List },
  multi_select: { name: 'Pick several', description: 'Tick all the answers that apply.', icon: ListChecks },
  lookup: { name: 'Search a list', description: 'Pick from a long drop-down list, with a search box.', icon: Search },
  date: { name: 'Date', description: 'A calendar date.', icon: Calendar },
  time: { name: 'Time', description: 'A time of day.', icon: Clock },
  duration: { name: 'Length of time', description: 'How long, in days, months or years, such as time in business.', icon: Hourglass },
  business_hours: { name: 'Business hours', description: 'Opening and closing times for weekdays, weekends and holidays.', icon: CalendarClock },
  datetime: { name: 'Date and time', description: 'A date with a time.', icon: CalendarClock },
  address: { name: 'Address', description: 'A South African address, optionally with a map pin.', icon: MapPin },
  location_pin: { name: 'Map pin', description: 'The agent drops a pin on a map.', icon: MapIcon },
  current_location: { name: 'Current GPS location', description: "Records the phone's GPS position.", icon: Navigation },
  photo: { name: 'Photos', description: 'Camera photos with GPS and a minimum / maximum count.', icon: Camera },
  signature: { name: 'Signature', description: 'A signature drawn on the screen.', icon: PenLine },
  declaration: { name: 'Declaration', description: 'The agent agrees to a declaration statement.', icon: FileSignature },
  acknowledgement: { name: 'Tick to confirm', description: 'A statement the agent must tick to continue.', icon: CheckSquare },
  consent: { name: 'Consent', description: 'The person being interviewed agrees to a consent statement.', icon: ShieldCheck },
  info: { name: 'Information text', description: 'A paragraph of guidance for the agent. Not a question.', icon: Info },
  callout: { name: 'Highlighted notice', description: 'A coloured notice, such as a warning. Not a question.', icon: MessageSquareWarning },
  divider: { name: 'Divider line', description: 'A line that separates parts of a page.', icon: Minus },
  image: { name: 'Picture', description: 'An instructional image.', icon: Image },
  prefilled: { name: 'Copied from the job', description: 'Shows a value copied from the job or the agent, which the agent can flag as different.', icon: FileText },
  computed: { name: 'Calculated value', description: 'A value worked out from other answers, such as a score.', icon: Calculator },
  group: { name: 'Group', description: 'Keeps several questions together (optionally in two columns).', icon: Square },
  repeatable_group: { name: 'Repeating group', description: 'A set of questions the agent can fill in several times, such as once for each other business.', icon: Repeat },
  matrix: { name: 'Grid of questions', description: 'Rows of questions sharing the same answer columns.', icon: Columns3 },
};

export function componentWording(type: string): Wording {
  return COMPONENT_WORDING[type] ?? { name: humanLabel(type), description: 'Another kind of question.', icon: Sparkles };
}

const DISPLAY_LABEL: Record<string, string> = {
  single_line: 'Single line',
  multi_line: 'Multiple lines',
  plain: 'Plain box',
  stepper: 'Stepper (− / +)',
  slider: 'Slider',
  yes_no_radio: 'Yes / No buttons',
  toggle: 'Switch',
  checkbox: 'Checkbox',
  segmented: 'Segmented buttons',
  radio: 'Radio buttons',
  dropdown: 'Dropdown',
  chips: 'Chips',
  searchable_list: 'Searchable list',
  checkboxes: 'Checkboxes',
  searchable_sheet: 'Searchable sheet',
  grid: 'Grid of photos',
  guided_sequence: 'Guided, one photo at a time',
  stars: 'Stars',
  numbered: 'Numbers',
  likert: 'Agree / disagree scale',
};

export const displayLabel = (d: string): string => DISPLAY_LABEL[d] ?? humanLabel(d);

/** Friendly labels and hints for component props (docs/11). Unlisted props fall back to a humanised key. */
export const PROP_LABEL: Record<string, { label: string; hint?: string }> = {
  min_length: { label: 'Minimum characters' },
  max_length: { label: 'Maximum characters' },
  pattern: { label: 'Format (pattern)', hint: 'A pattern the answer must match, written as a regular expression. For six digits: ^[0-9]{6}$' },
  mask: { label: 'Input mask' },
  placeholder: { label: 'Hint inside the box' },
  keyboard: { label: 'Keyboard' },
  capitalise: { label: 'Capital letters' },
  rows: { label: 'Height (lines)' },
  min: { label: 'Lowest allowed' },
  max: { label: 'Highest allowed' },
  integer: { label: 'Whole numbers only' },
  decimals: { label: 'Decimal places' },
  unit: { label: 'Unit', hint: 'Shown after the number, such as m² or days.' },
  step: { label: 'Step size' },
  default_region: { label: 'Default country code', hint: 'Two letters, such as ZA.' },
  allow_landline: { label: 'Allow landline numbers' },
  currency: { label: 'Currency', hint: 'Three letters, such as ZAR.' },
  min_label: { label: 'Label at the low end' },
  max_label: { label: 'Label at the high end' },
  scale: { label: 'Scale (3–10)' },
  labels: { label: 'Labels' },
  scheme: { label: 'Kind of number' },
  true_label: { label: 'Label for Yes' },
  false_label: { label: 'Label for No' },
  allow_other: { label: 'Offer "Other" with a text box' },
  other_value: { label: 'Value stored for "Other"' },
  other_label: { label: 'Label for "Other"' },
  min_select: { label: 'Tick at least' },
  max_select: { label: 'Tick at most' },
  exclusive_options: { label: 'Answers that clear the others', hint: 'Such as “None of the above”.' },
  list: { label: 'Drop-down list' },
  search: { label: 'Show a search box' },
  allow_unknown: { label: 'Allow "Unknown"' },
  units: { label: 'Units the agent can choose' },
  groups: { label: 'Day groups' },
  allow_24h: { label: 'Allow "Open 24 hours"' },
  map_pin: { label: 'Map pin' },
  geocode: { label: 'Look up the address on a map' },
  provinces: { label: 'Provinces offered' },
  initial: { label: 'Map starts at' },
  max_distance_from_job_m: { label: 'Maximum distance from the job (m)' },
  max_accuracy_m: { label: 'Required GPS accuracy (m)' },
  sample_seconds: { label: 'GPS sampling time (seconds)' },
  min_count: { label: 'Minimum photos' },
  max_count: { label: 'Maximum photos' },
  category: { label: 'Photo group', hint: 'Groups the photos on the review screen and in exports, such as “external”.' },
  require_gps: { label: 'Photos must carry a GPS location' },
  guidance: { label: 'Guidance for the agent' },
  caption: { label: 'Caption' },
  retake: { label: 'Retaking a photo' },
  signer_name_field: { label: "Signer's name comes from" },
  signer_designation_field: { label: "Signer's role comes from" },
  min_stroke_length: { label: 'Minimum signature length' },
  declaration_key: { label: 'Declaration text' },
  text: { label: 'Text' },
  by_name_field: { label: 'Name of the person comes from' },
  tone: { label: 'Colour' },
  asset: { label: 'Image' },
  source: { label: 'Copied from' },
  allow_flag_differs: { label: 'Agent can flag that it differs' },
  differs_note: { label: 'Prompt when it differs' },
  format: { label: 'Show as' },
  hidden: { label: 'Hide from the agent' },
  layout: { label: 'Layout' },
  min_items: { label: 'At least (items)' },
  max_items: { label: 'At most (items)' },
  item_label: { label: 'Name of each item' },
  add_label: { label: 'Label of the add button' },
  cell_type: { label: 'Answer type in each cell' },
  required_rows: { label: 'Rows that must be answered' },
  columns: { label: 'Columns' },
};

export const propLabel = (key: string): { label: string; hint?: string } => PROP_LABEL[key] ?? { label: humanLabel(key) };

const ENUM_VALUE_LABEL: Record<string, string> = {
  none: 'None',
  words: 'Each word',
  sentences: 'Start of each sentence',
  characters: 'All capitals',
  text: 'Text',
  number: 'Numbers',
  phone: 'Phone',
  email: 'Email',
  url: 'Web address',
  optional: 'Optional',
  required: 'Required',
  off: 'Off',
  when_online: 'When online',
  job: 'The job location',
  current: "The agent's location",
  allowed: 'Allowed',
  confirm: 'Ask to confirm',
  disallowed: 'Not allowed',
  info: 'Blue (information)',
  warning: 'Amber (warning)',
  danger: 'Red (danger)',
  neutral: 'Grey',
  success: 'Green',
  stack: 'One under the other',
  two_column: 'Two columns',
  single: 'Pick one',
  multi: 'Pick several',
  za_id: 'SA ID number',
  passport: 'Passport',
  custom: 'Custom pattern',
  cipc: 'CIPC registration',
  vat_za: 'SA VAT number',
  days: 'Days',
  months: 'Months',
  years: 'Years',
  weekdays: 'Weekdays',
  saturday: 'Saturday',
  sunday: 'Sunday',
  public_holidays: 'Public holidays',
  percentage: 'Percentage',
  date: 'Date',
  datetime: 'Date and time',
  asc: 'Oldest / smallest first',
  desc: 'Newest / largest first',
  section_per_page: 'One section per page',
  single_page: 'All on one page',
  profile: 'Depends on the location profile',
  always: 'Always',
  primary: 'Main (filled)',
  secondary: 'Secondary (outline)',
  local: 'Records on the phone',
  server: 'Total from the server',
  jobs: 'Jobs',
  inspections: 'Visits',
  form_submissions: 'Answers sent in',
  call: 'Call',
  sms: 'SMS',
  bottom_tabs: 'Tabs along the bottom',
  drawer: 'Side menu',
  saved: 'Saved on the phone',
  failure: 'Could not be completed',
  agent: 'The agent',
  home: 'Go home',
  receipt: 'Show the confirmation',
  retry: 'Try again',
  start_flow: 'Start visit steps',
  page: 'Open a page',
  back: 'Go back',
  currency_value: 'Currency',
};

export const enumLabel = (v: string): string => ENUM_VALUE_LABEL[v] ?? humanLabel(v);

// ── Flow steps ─────────────────────────────────────────────────────────────────────────────────
const STEP_WORDING: Record<string, Wording> = {
  job_briefing: { name: 'Job briefing', description: 'Shows the job details before the agent starts.', icon: ClipboardCheck },
  location_check: { name: 'Location check', description: 'Checks the agent is inside the site area around the merchant, with a way to carry on if not.', icon: MapPin },
  form: { name: 'Questions', description: 'Shows one or more sections of the chosen questions.', icon: LayoutList },
  summary_review: { name: 'Review answers', description: 'The agent checks every answer before the declaration.', icon: ListChecks },
  declaration: { name: 'Agent declaration', description: 'The agent agrees to the declaration statement.', icon: FileSignature },
  submit: { name: 'Submit', description: 'Locks the answers and photos and sends them to the office.', icon: Send },
  receipt: { name: 'Confirmation', description: 'Shows what the office received.', icon: Receipt },
};

export function stepWording(type: string): Wording {
  return STEP_WORDING[type] ?? { name: humanLabel(type), description: 'A step of the visit.', icon: Workflow };
}

export const ACTION_LABEL: Record<string, string> = {
  'job.accept': 'Accept the job',
  'job.reject': 'Turn down the job',
  'job.unable': 'Mark the job as not possible to do',
  'inspection.start': 'Start the visit',
  'inspection.submit': 'Send the visit in',
  'record.submit': 'Save the answers as a record',
  'lead.create': 'Create a lead (not decided yet)',
  navigate: 'Go to a page',
  'panic.raise': 'Raise a panic alert (not available yet)',
};

// ── View components ────────────────────────────────────────────────────────────────────────────
const VIEW_WORDING: Record<string, Wording> = {
  title: { name: 'Title', description: 'A large heading, from a job value or fixed text.', icon: Heading1 },
  field_value: { name: 'Label and value', description: 'One job detail with its label, such as the reference.', icon: Type },
  address_block: { name: 'Address', description: 'A formatted address.', icon: MapPin },
  map_preview: { name: 'Map', description: 'A small map at a location.', icon: MapIcon },
  contact: { name: 'Contact', description: 'A person with call / SMS buttons.', icon: Contact },
  schedule_window: { name: 'Visit window', description: 'The scheduled date and time window.', icon: CalendarClock },
  status_chip: { name: 'Status', description: 'The job status as a coloured chip.', icon: Tag },
  badge: { name: 'Badge', description: 'A small coloured label.', icon: BadgeIcon },
  markdown: { name: 'Text', description: 'A paragraph of text (may include job values).', icon: ScrollText },
  image: { name: 'Picture', description: 'An image.', icon: Image },
  divider: { name: 'Divider line', description: 'A separating line.', icon: Minus },
  evidence_status: { name: 'Photo upload status', description: 'How many photos the office has received and checked.', icon: Fingerprint },
  greeting: { name: 'Greeting', description: 'A welcome line, such as “Hi Gugu”.', icon: Smile },
  section_title: { name: 'Section heading', description: 'A small heading between parts of the home page.', icon: Heading1 },
  stat_row: { name: 'Row of totals', description: 'A row of tiles with counts, such as Active or Due today.', icon: BarChart3 },
  stat_tile: { name: 'Total tile', description: 'One count, from the phone or from the server.', icon: Hash },
  job_list: { name: 'List of jobs', description: 'A filtered list of the agent’s jobs.', icon: LayoutList },
  agent_card_summary: { name: 'Authorisation card (small)', description: "A summary of the agent's card; tap to open it.", icon: CreditCard },
  action_button: { name: 'Button', description: 'A button that opens a page or starts visit steps.', icon: MousePointerClick },
  sync_status: { name: 'Sync status', description: 'Whether everything has uploaded.', icon: RefreshCw },
  announcement: { name: 'Announcement', description: 'A coloured message for all agents.', icon: Megaphone },
  agent_card: { name: 'Agent authorisation card', description: "The agent's card with photo and QR code.", icon: UserRound },
  job_card: { name: 'Job card', description: 'The job summary card with QR code.', icon: Flag },
};

export function viewWording(type: string): Wording {
  return VIEW_WORDING[type] ?? { name: humanLabel(type), description: 'Something shown on the screen.', icon: Sparkles };
}

export const VIEW_GROUP_LABEL: Record<string, string> = { display: 'Job and record details', home: 'Home page', card: 'Cards' };

// ── Page types ─────────────────────────────────────────────────────────────────────────────────
const PAGE_WORDING: Record<string, Wording> = {
  view_page: { name: 'Screen', description: 'Shows a screen layout, such as the home page or the job page.', icon: PanelTop },
  list_page: { name: 'List', description: 'A list of jobs or records, such as active leads.', icon: LayoutList },
  form_page: { name: 'Questions page', description: 'A set of questions that does one thing when sent, such as turning down a job.', icon: FileText },
  flow: { name: 'Visit steps', description: 'Runs visit steps, such as the site visit.', icon: Workflow },
  outcome_page: { name: 'Result', description: 'What the agent sees after submitting: success, saved or failure.', icon: Receipt },
};

export function pageWording(type: string): Wording {
  return PAGE_WORDING[type] ?? { name: humanLabel(type), description: 'A page.', icon: Link2 };
}

export const NAV_ICONS = ['home', 'list', 'badge', 'person', 'map', 'calendar', 'settings', 'help', 'search', 'notifications', 'camera', 'assignment'] as const;

