#!/usr/bin/env node
// Vendor the TS engine into the Supabase Edge Functions tree (Deno).
//
//   node tools/vendor-engine.mjs            → supabase/functions/_shared/engine/
//   node tools/vendor-engine.mjs <dest-dir> → any other directory (e.g. a temp dir for testing)
//
// Copies packages/fess_pos_engine_ts/src/**/*.ts, prefixes each file with a GENERATED header naming its
// source, and rewrites the bare `zod` import to `npm:zod@<version from the package's dependencies>` so
// Deno resolves it without an import map. Refuses to overwrite a destination that holds files it did not
// generate. No dependencies; Node 20+.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkgDir = join(repo, "packages", "fess_pos_engine_ts");
const srcDir = join(pkgDir, "src");
const dest = resolve(process.argv[2] ?? join(repo, "supabase", "functions", "_shared", "engine"));
const MARKER = "// GENERATED — do not edit.";

const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8"));
const zodRange = pkg.dependencies?.zod;
if (!zodRange) {
  console.error("vendor-engine: packages/fess_pos_engine_ts/package.json has no zod dependency");
  process.exit(1);
}
const zodSpecifier = `npm:zod@${zodRange}`;

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : p.endsWith(".ts") ? [p] : [];
  });
}

if (existsSync(dest)) {
  const foreign = walk(dest).filter((f) => !readFileSync(f, "utf8").startsWith(MARKER));
  const others = readdirSync(dest).filter((n) => {
    const p = join(dest, n);
    return !statSync(p).isDirectory() && !n.endsWith(".ts");
  });
  if (foreign.length > 0 || others.length > 0) {
    console.error(`vendor-engine: ${dest} contains files not generated by this script; refusing to overwrite:`);
    for (const f of [...foreign, ...others.map((n) => join(dest, n))]) console.error(`  ${f}`);
    process.exit(1);
  }
  rmSync(dest, { recursive: true, force: true });
}

const files = walk(srcDir);
for (const file of files) {
  const rel = relative(srcDir, file);
  const sourcePath = ["packages", "fess_pos_engine_ts", "src", ...rel.split(sep)].join("/");
  const body = readFileSync(file, "utf8").replace(/(from\s+|import\s*\(\s*)(["'])zod\2/g, `$1$2${zodSpecifier}$2`);
  const header = `${MARKER} Source: ${sourcePath} (run: node tools/vendor-engine.mjs)\n`;
  const out = join(dest, rel);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, header + body);
}
console.log(`vendor-engine: ${files.length} files → ${relative(process.cwd(), dest) || dest} (zod → ${zodSpecifier})`);
